<a href="https://colab.research.google.com/github/Ozk18532/INTELIGENCIA-COMPUTACIONAL-Oscar-Mercado/blob/main/9_vectorstore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vector stores and semantic search

In [1]:
from sentence_transformers import SentenceTransformer

## Part I: Basic vector store implementation

In [2]:
#Clases base
class Document:
    def __init__(self, text: str, metadata: dict[str, str]):
        self.text = text
        self.metadata = metadata


class SearchResult:
    def __init__(self, score: float, document: Document):
        self.score = score
        self.document = document

#Implementación de VectorStore
class VectorStore:

    def __init__(self, embedding_model: SentenceTransformer):

        self.embedding_model = embedding_model

        self.documents = []

        self.embeddings = None


    def add_documents(self, documents: list[Document]):

        self.documents.extend(documents)

        texts = [doc.text for doc in self.documents]

        self.embeddings = self.embedding_model.encode(texts)

        print(f"{V}Documentos agregados correctamente{E}")
        print(f"{A}Total de documentos:{E}", len(self.documents))


    def search(self, query: str, top_k: int = 5) -> list[SearchResult]:

        # Embedding del query
        query_embedding = self.embedding_model.encode([query])

        # Similaridad coseno
        similarities = cosine_similarity(
            query_embedding,
            self.embeddings
        )[0]

        # Índices ordenados
        top_indices = np.argsort(similarities)[::-1][:top_k]

        results = []

        for idx in top_indices:

            result = SearchResult(
                score=float(similarities[idx]),
                document=self.documents[idx]
            )

            results.append(result)

        return results

## Part II: Filtering by metadata

In [3]:
class FilteredVectorStore:
    def __init__(self, embedding_model: SentenceTransformer):
        pass

    def add_documents(self, documents: list[Document]):
        pass

    def search(self,
               query: str,
               top_k: int = 5,
               metadata_filter: dict[str, str] | None = None) -> list[SearchResult]:
        pass



---



---

Instalación de librerías

In [4]:
!pip install sentence-transformers scikit-learn pandas numpy -q

In [5]:
# Imports y configuración
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer#⚠️
from sklearn.metrics.pairwise import cosine_similarity

#Colores
V = '\033[92m'  # Verde
R = '\033[91m'  # Rojo
A = '\033[94m'  # Azul
M = '\033[95m'  # Morado
E = '\033[0m'   # Fin color

print(f"{V}Librerías cargadas correctamente{E}")

Librerías cargadas correctamente



---

**Implementación de VectorStore**

En esta actividad se implementará un sistema básico de búsqueda semántica utilizando embeddings y cosine similarity.

Un VectorStore es una estructura que almacena documentos junto con sus representaciones vectoriales (embeddings). Estos embeddings permiten encontrar documentos similares semánticamente incluso cuando las palabras exactas no coinciden.

Para esta práctica se utilizará el dataset Animal Fun Facts Dataset.

Cada documento tendrá:

- Texto principal (`text`)
- Metadatos:
  - `animal_name`
  - `source`
  - `media_link`
  - `wikipedia_link`

Posteriormente se implementará:

- Clase `Document`
- Clase `SearchResult`
- Clase `VectorStore`

Finalmente se realizarán búsquedas semánticas mostrando:
- score de similitud
- texto
- metadatos



---
**Carga del dataset Animal Fun Facts**

In [6]:
import pandas as pd

url = "https://raw.githubusercontent.com/ekohrt/animal-fun-facts-dataset/main/animal-fun-facts-dataset.csv"

df = pd.read_csv(url)

print(f"{V}Dataset cargado correctamente{E}")
print(df.shape)

Dataset cargado correctamente
(7734, 5)

In [7]:
print(f"{A}Dimensiones del dataset:{E}", df.shape)

df.head()

Dimensiones del dataset: (7734, 5)

,animal_name,source,text,media_link,wikipedia_link
0,aardvark,https://www.animalfactsencyclopedia.com/Aardva...,"Aardvarks are sometimes called ""ant bears"", ""e...",NaN,/wiki/Aardvark
1,aardvark,https://www.animalfactsencyclopedia.com/Aardva...,Aardvarks\nhave rather primitive brains that a...,NaN,/wiki/Aardvark
2,aardvark,https://www.animalfactsencyclopedia.com/Aardva...,Aardvarks\nteeth are lined with fine upright t...,NaN,/wiki/Aardvark
3,aardvark,https://www.animalfactsencyclopedia.com/Aardva...,"The aardvarks Latin family name ""Tubulidentata...",NaN,/wiki/Aardvark
4,aardvark,https://www.animalfactsencyclopedia.com/Aardva...,Baby aardvarks are born with front teeth that ...,NaN,/wiki/Aardvark



---
**Conversión del dataset a documentos**

In [8]:
documents = []

for _, row in df.iterrows():

    metadata = {
        "animal_name": str(row["animal_name"]),
        "source": str(row["source"]),
        "media_link": str(row["media_link"]),
        "wikipedia_link": str(row["wikipedia_link"])
    }

    document = Document(
        text=str(row["text"]),
        metadata=metadata
    )

    documents.append(document)

print(f"{V}Documentos creados correctamente{E}")

print(f"{A}Cantidad total:{E}", len(documents))

Documentos creados correctamente
Cantidad total: 7734



---
**Modelo de embeddings**

In [9]:
embedding_model = SentenceTransformer(
    'all-MiniLM-L6-v2'
)

print(f"{V}Modelo de embeddings cargado correctamente{E}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Modelo de embeddings cargado correctamente


---
**Crear VectorStore y agregar documentos**

In [10]:
vector_store = VectorStore(
    embedding_model=embedding_model
)

vector_store.add_documents(documents)

Documentos agregados correctamente
Total de documentos: 7734



---
**Función para mostrar resultados**

In [11]:
def mostrar_resultados(results):

    for i, result in enumerate(results):

        print(f"{M}=============================={E}")
        print(f"{V}Resultado #{i+1}{E}")

        print(f"{A}Score:{E} {result.score:.4f}")

        print(f"{A}Texto:{E}")
        print(result.document.text)

        print(f"{A}Metadatos:{E}")

        for key, value in result.document.metadata.items():
            print(f"  - {key}: {value}")

        print()



---
**Búsqueda 1**

In [12]:
query = "animals that can fly"

print(f"{R}Consulta:{E}", query)

results = vector_store.search(query)

mostrar_resultados(results)

Consulta: animals that can fly
==============================
Resultado #1
Score: 0.7076
Texto:
They don’t fly, they glide.
The only mammal which can independently fly is the bat. Instead, colugas glide which works in the same way as a wingsuit.
Metadatos:
  - animal_name: colugo (flying lemur)
  - source: https://factanimal.com/colugo/
  - media_link: nan
  - wikipedia_link: /wiki/Colugo

==============================
Resultado #2
Score: 0.6901
Texto:
Not all birds are able to fly!
Metadatos:
  - animal_name: bird
  - source: https://a-z-animals.com/animals/bird/
  - media_link: nan
  - wikipedia_link: /wiki/Bird

==============================
Resultado #3
Score: 0.6481
Texto:
They rarely fly..
They move around on foot most of the time, only taking to the air to reach their nests or for courtship displays.
Metadatos:
  - animal_name: secretary bird
  - source: https://factanimal.com/secretarybird/
  - media_link: nan
  - wikipedia_link: /wiki/Secretarybird

==============================
Resultado #4
Score: 0.6437
Texto:
Bats are the only mammals with wings, and the only ones that can truly fly
Metadatos:
  - animal_name: bat
  - source: https://www.animalfactsencyclopedia.com/Bat-facts.html
  - media_link: nan
  - wikipedia_link: /wiki/Bat

==============================
Resultado #5
Score: 0.6423
Texto:
Flamingos can fly!.
Flamingos kept in zoo’s have often had their wings clipped. In the wild, flamingos can fly, and they use their wings to migrate to warmer areas for winter and to search new bodies of water for food.
Metadatos:
  - animal_name: flamingo
  - source: https://factanimal.com/flamingo/
  - media_link: nan
  - wikipedia_link: /wiki/Flamingo



---
**Búsqueda 2**

In [13]:
query = "animals that live underwater"

print(f"{R}Consulta:{E}", query)#⚠️

results = vector_store.search(query)

mostrar_resultados(results)

Consulta: animals that live underwater
==============================
Resultado #1
Score: 0.7298
Texto:
They are semi-aquatic mammals..
They live in and around lakes, rivers, swamps, and tropical rivers. They are excellent at swimming and can hold their breath for 5 minutes at a time. They are well adapted for this, with partially webbed toes for swimming. Also, their eyes, ears and nose are high on their heads to watch out for predators when they are underwater. 2
Metadatos:
  - animal_name: capybara
  - source: https://factanimal.com/capybara/
  - media_link: nan
  - wikipedia_link: /wiki/Capybara

==============================
Resultado #2
Score: 0.7203
Texto:
They can stay submerged underwater for 6-8 mins.
They have large lungs, which allows this semi-aquatic animal to stay underwater for extended lengths of time.
Metadatos:
  - animal_name: beaver
  - source: https://factanimal.com/beaver/
  - media_link: nan
  - wikipedia_link: /wiki/Beaver

==============================
Resultado #3
Score: 0.6918
Texto:
They can’t survive underwater.
They do still have gills, but they’re more or less redundant. This means they are unable to stay in water for more than an hour or so and will drown if they’re unable to leave.
Metadatos:
  - animal_name: coconut crab
  - source: https://factanimal.com/coconut-crab/
  - media_link: nan
  - wikipedia_link: /wiki/Coconut_crab

==============================
Resultado #4
Score: 0.6714
Texto:
They breathe through gills but live on land
Metadatos:
  - animal_name: sea roach
  - source: https://a-z-animals.com/animals/sea-roach/
  - media_link: nan
  - wikipedia_link: /wiki/Ligia_oceanica

==============================
Resultado #5
Score: 0.6694
Texto:
They can live for up to 30 hours in water..
Horrifyingly, they sometimes fall in suburban swimming pools, where they can survive underwater for 30 hours.
Metadatos:
  - animal_name: sydney funnel-web spider
  - source: https://factanimal.com/sydney-funnel-web-spider/
  - media_link: nan
  - wikipedia_link: /wiki/Sydney_funnel-web_spider



---
**Búsqueda 3**

In [14]:
query = "dangerous predators"

print(f"{R}Consulta:{E}", query)#⚠️

results = vector_store.search(query)

mostrar_resultados(results)

Consulta: dangerous predators
==============================
Resultado #1
Score: 0.6970
Texto:
Has no real natural predators!
Metadatos:
  - animal_name: buffalo
  - source: https://a-z-animals.com/animals/buffalo/
  - media_link: nan
  - wikipedia_link: /wiki/Bison

==============================
Resultado #2
Score: 0.6970
Texto:
Has no real natural predators!
Metadatos:
  - animal_name: mountain lion
  - source: https://a-z-animals.com/animals/mountain-lion/
  - media_link: nan
  - wikipedia_link: /wiki/Cougar

==============================
Resultado #3
Score: 0.6654
Texto:
A dominant predator in it's environment!
Metadatos:
  - animal_name: brown bear
  - source: https://a-z-animals.com/animals/brown-bear/
  - media_link: nan
  - wikipedia_link: /wiki/Brown_bear

==============================
Resultado #4
Score: 0.6632
Texto:
A very bold and ferocious predator!
Metadatos:
  - animal_name: ermine
  - source: https://a-z-animals.com/animals/ermine/
  - media_link: nan
  - wikipedia_link: /wiki/Stoat

==============================
Resultado #5
Score: 0.6511
Texto:
In the event of a predator, they will act as a group and fight to protect each other.
Metadatos:
  - animal_name: slender-tailed meerkat
  - source: https://seaworld.org/animals/facts/mammals/slender-tailed-meerkat/
  - media_link: nan
  - wikipedia_link: /wiki/Meerkat



---
**Búsqueda 4**

In [15]:
query = "animals with strong memory"

print(f"{R}Consulta:{E}", query)#⚠️

results = vector_store.search(query)

mostrar_resultados(results)

Consulta: animals with strong memory
==============================
Resultado #1
Score: 0.5720
Texto:
opossums have better memories than rats, cats, dogs and even pigs.
Metadatos:
  - animal_name: opossum
  - source: /r/AskReddit/comments/gbh7zz/what_are_some_really_amazing_animal_facts/fp65hrs/
  - media_link: nan
  - wikipedia_link: /wiki/Opossum

==============================
Resultado #2
Score: 0.5640
Texto:
Some dogs can recognize over 1000 words
Metadatos:
  - animal_name: dog
  - source: https://www.animalfactsencyclopedia.com/All-About-Dogs.html
  - media_link: nan
  - wikipedia_link: /wiki/Dog

==============================
Resultado #3
Score: 0.5558
Texto:
The red squirrel has one of the most impressive memories in the entire animal kingdom
Metadatos:
  - animal_name: red squirrel
  - source: https://a-z-animals.com/animals/red-squirrel/
  - media_link: nan
  - wikipedia_link: /wiki/Red_squirrel

==============================
Resultado #4
Score: 0.5049
Texto:
Highly active and intelligent dogs!
Metadatos:
  - animal_name: bedlington terrier
  - source: https://a-z-animals.com/animals/bedlington-terrier/
  - media_link: nan
  - wikipedia_link: /wiki/Bedlington_Terrier

==============================
Resultado #5
Score: 0.4919
Texto:
This gigantic breed is known for its guardian skills, but they are non-aggressive and always manage to stay calm towards people and animals.
Metadatos:
  - animal_name: polish tatra sheepdog
  - source: https://a-z-animals.com/animals/polish-tatra-sheepdog/
  - media_link: nan
  - wikipedia_link: /wiki/Tatra_Shepherd_Dog



---
**Búsqueda 5**

In [16]:
query = "fast animals"

print(f"{R}Consulta:{E}", query)#⚠️

results = vector_store.search(query)

mostrar_resultados(results)

Consulta: fast animals
==============================
Resultado #1
Score: 0.8064
Texto:
Fastest animal on Earth
Metadatos:
  - animal_name: peregrine falcon
  - source: https://a-z-animals.com/animals/peregrine-falcon/
  - media_link: nan
  - wikipedia_link: /wiki/Peregrine_falcon

==============================
Resultado #2
Score: 0.7487
Texto:
The fastest creatures on the planet!
Metadatos:
  - animal_name: falcon
  - source: https://a-z-animals.com/animals/falcon/
  - media_link: nan
  - wikipedia_link: /wiki/Falcon

==============================
Resultado #3
Score: 0.6795
Texto:
The fastest land mammal in the world!
Metadatos:
  - animal_name: cheetah
  - source: https://a-z-animals.com/animals/cheetah/
  - media_link: nan
  - wikipedia_link: /wiki/Cheetah

==============================
Resultado #4
Score: 0.6764
Texto:
Patagonian mara are the worlds fastest rodent
.
On that topic, they can really move! Plains animals often use speed to their advantage (think cheetahs and gazelles), but the mara is a record-holder in that department.
Metadatos:
  - animal_name: patagonian mara
  - source: https://factanimal.com/patagonian-mara/
  - media_link: nan
  - wikipedia_link: /wiki/Patagonian_mara

==============================
Resultado #5
Score: 0.6647
Texto:
They’re apparently the fastest animal in the ocean.
Early estimates of the speed of sailfish from the ‘40s suggested it could swim at bursts of up to 67mph, making it significantly faster than pretty much everything in the ocean.
Metadatos:
  - animal_name: sailfish
  - source: https://factanimal.com/sailfish/
  - media_link: nan
  - wikipedia_link: /wiki/Sailfish

# Conclusión parcial

Durante esta primera parte se implementó un VectorStore básico utilizando embeddings y cosine similarity.

El sistema logró encontrar documentos similares semánticamente utilizando lenguaje natural, sin depender únicamente de coincidencias exactas de palabras.

Además, se cargó correctamente el Animal Fun Facts Dataset como objetos de tipo `Document`, separando el texto principal de sus metadatos.

Las búsquedas realizadas demostraron cómo los embeddings permiten recuperar información relacionada conceptualmente con cada consulta.



---

# **Explicación de FilteredVectorStore**


En esta segunda parte se implementará un sistema de búsqueda semántica con filtros de metadatos.

La diferencia principal entre `VectorStore` y `FilteredVectorStore` es que este último permite restringir los resultados utilizando información adicional almacenada en los metadatos.

Por ejemplo:
- categoría
- autor
- año
- sentimiento
- tipo de contenido

Esto permite realizar búsquedas mucho más específicas y organizadas.

Para esta práctica se utilizará un pequeño dataset de noticias tecnológicas y deportivas creado manualmente.



---
**Carga del dataset secundario (NIFTY)**

En esta sección se utilizará el dataset **NIFTY**, el cual contiene noticias y registros relacionados con el entorno financiero.  
La información incluye texto natural acompañado de múltiples metadatos, lo que permite realizar búsquedas, filtrados y análisis más completos dentro del VectorStore.

###  Contenido principal
- Titulares de noticias financieras
- Texto descriptivo relacionado con mercados y economía
- Contexto económico asociado a cada registro

###  Metadatos disponibles
- Índices bursátiles
- Fechas y timestamps
- Rankings o puntuaciones
- Labels y categorías financieras

###  Aplicaciones posibles
- Clasificación de texto financiero
- Análisis de lenguaje natural (NLP)
- Búsquedas filtradas por metadata
- Modelado temporal de noticias
- Sistemas de recomendación y recuperación semántica

In [17]:
!pip install datasets -q

from datasets import load_dataset
#⚠️
ds = load_dataset("raeidsaqur/NIFTY")

print(f"{V}Dataset NIFTY cargado correctamente{E}")

print(ds)

Dataset NIFTY cargado correctamente
DatasetDict({
    train: Dataset({
        features: ['id', 'date', 'context', 'news', 'conversations', 'label', 'pct_change'],
        num_rows: 1477
    })
    test: Dataset({
        features: ['id', 'date', 'context', 'news', 'conversations', 'label', 'pct_change'],
        num_rows: 317
    })
    valid: Dataset({
        features: ['id', 'date', 'context', 'news', 'conversations', 'label', 'pct_change'],
        num_rows: 317
    })
})



---
**Exploración del dataset**

In [18]:
df_nifty = ds["train"].to_pandas()

print(f"{A}Dimensiones:{E}", df_nifty.shape)

df_nifty.head()

Dimensiones: (1477, 7)

,id,date,context,news,conversations,label,pct_change
0,nifty_0,2010-01-06,"date,open,high,low,close,adj_close,volume,pct_...",China Officials Likely Knew of Bad Milk\nSony'...,"[{'role': 'user', 'value': 'Project the $SPY i...",Neutral,0.0042
1,nifty_1,2010-01-07,"date,open,high,low,close,adj_close,volume,pct_...",Britain Set for Next Step on Wind Power\nJourn...,"[{'role': 'user', 'value': 'Analyze market dat...",Neutral,0.0033
2,nifty_2,2010-01-11,"date,open,high,low,close,adj_close,volume,pct_...","HK, China stocks rise on reforms; brokerages s...","[{'role': 'user', 'value': 'Forecast the $SPY ...",Fall,-0.0093
3,nifty_3,2010-01-12,"date,open,high,low,close,adj_close,volume,pct_...",DemandTec Names Retail Challenge Grand Final W...,"[{'role': 'user', 'value': 'Forecast the $SPY ...",Rise,0.0084
4,nifty_4,2010-01-13,"date,open,high,low,close,adj_close,volume,pct_...",Gear Malfunction Suspected in United Jet Incid...,"[{'role': 'user', 'value': 'Forecast the $SPY ...",Neutral,0.0027



---
**Ver columnas disponibles**

In [19]:
print(f"{V}Columnas disponibles:{E}")

print(df_nifty.columns)#⚠️

Columnas disponibles:
Index(['id', 'date', 'context', 'news', 'conversations', 'label',
       'pct_change'],
      dtype='object')



---
**Crear FilteredVectorStore**

Dataset secundario: NIFTY

Para esta segunda parte se utilizará el dataset NIFTY.

Este dataset contiene textos relacionados con noticias financieras y económicas acompañadas de diferentes metadatos.

El objetivo será implementar un `FilteredVectorStore` que permita realizar búsquedas semánticas restringidas utilizando filtros sobre dichos metadatos.



---
**Conversión del dataset NIFTY a documentos**

In [20]:
filtered_documents = []

for _, row in df_nifty.iterrows():

    metadata = {

        "id": str(row["id"]),

        "date": str(row["date"]),

        "context": str(row["context"]),

        "label": str(row["label"]),

        "pct_change": str(row["pct_change"])
    }

    document = Document(

        text=str(row["news"]),

        metadata=metadata
    )

    filtered_documents.append(document)

print(f"{V}Documentos creados correctamente{E}")

print(f"{A}Cantidad total:{E}", len(filtered_documents))

Documentos creados correctamente
Cantidad total: 1477



---
**Visualización de ejemp**lo

In [21]:
example_doc = filtered_documents[0]

print(f"{M}=============================={E}")

print(f"{V}Texto:{E}")

print(example_doc.text)

print()

print(f"{A}Metadatos:{E}")

for key, value in example_doc.metadata.items():#⚠️

    print(f"- {key}: {value}")

==============================
Texto:
China Officials Likely Knew of Bad Milk
Sony's CEO on Strategy in 3-D Technology
Copper Settles at 16-Month High
Gold Ends Near 3-Week High
Kraft Gets Antitrust Clearance
European Stocks Close Flat
M&S Sales Miss Expectations
Yen Boosts Japan's Exporters
Future Group: Value Retail Unit May Consider IPO
Dollar, Yen Gain on Haven Plays
Clothing Sales Sagged in December
Luxury Logos Draw Asian Shoppers
Mexican Stocks Have Record in Sight
Cold Snap Heats Up OJ Prices
Citi's Havens Got $9 Million for '09
TCW Will Quit U.S. Program
Scripps to Offer Free Show in Cablevision Feud
Two Pilots Die in Small-Jet Crash

Metadatos:
- id: nifty_0
- date: 2010-01-06 00:00:00
- context: date,open,high,low,close,adj_close,volume,pct_change,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma
- label: Neutral
- pct_change: 0.0042



---
**Implementación de FilteredVectorStore**

In [22]:
class FilteredVectorStore:

    def __init__(self, embedding_model: SentenceTransformer):#⚠️

        self.embedding_model = embedding_model

        self.documents = []

        self.embeddings = None


    def add_documents(self, documents: list[Document]):

        self.documents.extend(documents)

        texts = [doc.text for doc in self.documents]

        self.embeddings = self.embedding_model.encode(texts)

        print(f"{V}Documentos agregados correctamente{E}")

        print(f"{A}Total de documentos:{E}", len(self.documents))


    def search(
        self,
        query: str,
        top_k: int = 2,
        metadata_filter: dict[str, str] | None = None
    ) -> list[SearchResult]:

        filtered_docs = []

        filtered_embeddings = []

        for idx, doc in enumerate(self.documents):

            include_document = True

            if metadata_filter is not None:

                for key, value in metadata_filter.items():

                    if doc.metadata.get(key) != value:

                        include_document = False

                        break

            if include_document:#⚠️

                filtered_docs.append(doc)

                filtered_embeddings.append(self.embeddings[idx])

        if len(filtered_docs) == 0:

            print(f"{R}No se encontraron documentos con ese filtro{E}")

            return []

        query_embedding = self.embedding_model.encode([query])

        similarities = cosine_similarity(
            query_embedding,
            filtered_embeddings
        )[0]

        top_indices = np.argsort(similarities)[::-1][:top_k]

        results = []

        for idx in top_indices:

            result = SearchResult(

                score=float(similarities[idx]),

                document=filtered_docs[idx]
            )

            results.append(result)

        return results



---
Crear FilteredVectorStore

In [23]:
filtered_vector_store = FilteredVectorStore(
    embedding_model=embedding_model#⚠️
)

filtered_vector_store.add_documents(filtered_documents)

Documentos agregados correctamente
Total de documentos: 1477

In [24]:
print(f"{V}Valores únicos de label:{E}")

print(df_nifty["label"].unique())

print()

print(f"{V}Valores únicos de context:{E}")

print(df_nifty["context"].unique()[:10])

print()

print(f"{V}Primeras fechas:{E}")

print(df_nifty["date"].head())

Valores únicos de label:
['Neutral' 'Fall' 'Rise']

Valores únicos de context:
['date,open,high,low,close,adj_close,volume,pct_change,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma']

Primeras fechas:
0   2010-01-06
1   2010-01-07
2   2010-01-11
3   2010-01-12
4   2010-01-13
Name: date, dtype: datetime64[s]



---
**Búsqueda filtrada 1**

In [25]:
query = "stock market growth"

metadata_filter = {
    "label": "Rise"
}

print(f"{R}Consulta:{E}", query)

print(f"{A}Filtro:{E}", metadata_filter)

results = filtered_vector_store.search(#⚠️
    query=query,
    metadata_filter=metadata_filter
)

mostrar_resultados(results)

Consulta: stock market growth
Filtro: {'label': 'Rise'}
==============================
Resultado #1
Score: 0.4521
Texto:
Market Chatter- Corporate finance press digest
INDIA PRESS-Oberois to invest 10 bln rupees in Bangalore, Goa-Times of India
CNH Tracker-Banks launch new yuan FX options for companies in China
It may be too early to give up on the bull market in equities
MOVES-Vontobel Financial Products Asia Pacific names Thomas Sussli as head
PRESS DIGEST - Wall Street Journal - Aug 7
PRESS DIGEST- New York Times business news - Aug 7
China shares fall on weak energy, financials; HK down on casinos
Fraport Interim Report - 6 Months 2014: Financial Figures Grow as Expected
Japan's GPIF to boost stock allocation to over 20 pct - sources
Elektrobit Corporation's (EB) Interim Report January-June 2014
African Markets - Factors to watch on Aug 7
Deutsche Telekom Q2 core profit beats view on growth in U.S.
BRIEF-Inficon Holding says Q2 2014 sales of USD 74.8 million
NestlÃ© S.A. : First Half 2014: 4.7% organic growth in a volatile trading environment, CHF 8 billion share buy-back programme
Commerzbank speeds up clean-up, Q2 net profit doubles
BRIEF-Delhaize Q2 revenue rises 3.7 pct at identical exchange rates
StanChart clearly needs to take action: Asia CEO
Medigene significantly improves financial results for the first six months of 2014
Novo Nordisk A/S: Novo Nordisk increased operating profit in local currencies by 12% in the first six months of 2014
BOUSSARD AND GAVAUDAN HOLDING LIMITED (GBP) - Net Asset Value(s)
GFT Group Continues its Growth in First Half of 2014
NORDIC STOCKS - Factors to watch on Aug 7
Asia Day Ahead: China trade, Bank of Japan in the spotlight
Nikkei gains, yen dips after sources say GPIF may invest more in stocks
China diesel demand may post first fall in over a decade as economy slows
CFTC shows U.S. commodity manipulation laws have teeth: Kemp
Novo Nordisk A/S: Novo Nordisk increased operating profit in local currencies by 12% in the first six months of 2014
SE Asia Stocks -Thai shares trim losses, consumer confidence at 11-month high
BRIEF-Baywa says operating growth achievable if markets develop positively
GLOBAL MARKETS-Asia stocks slip, bonds firm on Ukraine tensions
Investments help Munich Re quarterly net profit jump
BRIEF-Gigaset Q2 consolidated revenue from continuing operations of EUR 82.0 million
Listings growth boosts Euronext Q2 profit
RPT-Investments help Munich Re quarterly net profit jump
UK Stocks-Factors to watch on Thursday August 7
East Capital Explorer AB - Fund Investment Performance July 2014
Western Bulk ASA - Second quarter 2014 results - dividend of NOK 0.64 per share
Advanced Semiconductor Engineering, Inc. Announces Monthly Net Revenues<2311.TW>
REG-First Trust Portfolios Form 8.3 - Carillion plc
Aviva plc: 2014 Interim Results Announcement
REG-First Trust Portfolios Form 8.3 - Carillion plc
REG-First Trust Portfolios Form 8.3 - Carillion plc
REG-First Trust Portfolios Form 8.3 - Carillion plc
REG-First Trust Portfolios Form 8.3 - Carillion plc
REG-First Trust Portfolios Form 8.3 - Carillion plc
REG-First Trust Portfolios Form 8.3 - Carillion plc
REG-First Trust Portfolios Form 8.3 - Carillion plc
REG-First Trust Portfolios Form 8.3 - Carillion plc
Nikkei gains after sources say GPIF plans to invest more in stocks
CORRECTED-In cat-and-mouse game, India uncovers new gold smuggling route
German industry output up 0.3 pct in June, misses forecast
RPT-Market Chatter- Corporate finance press digest
UPDATE 1-China finds shale gas challenging, halves 2020 output target
BRIEF-Rheinmetall down pre-market after profit warning
British pub firm Enterprise Inns optimistic as income grows
Japan regulators highlight interest rate risk; regional banks vulnerable to BOJ exit
BRIEF-North Media Q2 revenue DKK 276.9 million versus DKK 270.9 million
In cat-and-mouse game, India uncovers new gold smuggling route
BRIEF-Coca Cola HBC increases earnings in tough second-quarter market
Randgold CEO: Gold fix? We'll have two a day please
BRIEF-Sparebanken Moere Q2 net interest income NOK 268 million
Beiersdorf posts H1 EBIT growth of 4.3 percent
Hexagon Q2 profit just above forecasts
BRIEF-Savills says on track after first-half profit rises
BRIEF-BankNordik P/F Q2 net interest income DKK 126 million
BRIEF-Aspocomp reports Q2 EBITDA of EUR 0.3 million
NORDIC STOCKS - Factors to watch on Aug 7
China finds shale gas challenging, halves 2020 output target
Randgold Resources second-quarter profit rises
Western Bulk ASA - Announces a Change From Semi-Annual to Quarterly Dividend
ICL Reports Sharp Decline in Profitability in the Second Quarter
UPDATE 1-UK Stocks-Factors to watch on Thursday August 7
BRIEF-Taiwan's ASE posts 14.4 pct rise in July sales
Europe Factors to Watch-Shares set to pause; ECB eyed
FOREX-Yen slips as GPIF eyes stock allocation shift; Aussie hit by data
BRIEF-Transatlantic Q2 operating profit rises
German stocks - Factors to watch on August 7
RPT-BRIEF-Coca-Cola HBC increases earnings in tough second-quarter market
UPDATE 1-Nissan says July China auto sales fell 12.3 pct y/y
Swiss stocks - Factors to watch on Aug 7
UPDATE 1-Weak German industry output adds to signs of Q2 slowdown
UPDATE 2-Deutsche Telekom Q2 profit beats forecasts on U.S. growth
Weak German industry output adds to signs of second-quarter slowdown
Randgold Resources: 2nd Quarter Results and updates
Randgold Resources: 2nd Quarter Results and updates
TABLE-Foreign trading in Japan stocks for latest week
New date for delisting of Cision from NASDAQ OMX Stockholm â last day of trading set to 22 August 2014
Randgold Resources: 2nd Quarter Results and updates
Nestle announces share buyback as emerging markets pick up
Credit.com Unveils New iPhone Credit App
BRIEF-Adecco CEO weighing bolt-on buys to enhance technology
Russia's VTB says doesn't plan to issue new shares this year or in 2015
SNB forex reserves up in July
China shares post worst loss in 1-1/2 months as blue chips pull back
JGBs fall after sources say GPIF may invest more in stocks
China index: Beijing cleans up skies, not its act
European shares slip again, Commerzbank recovers
TABLE-Foreign trading in South Korean stocks
iDreamSky Announces Pricing of Initial Public Offering
Research and Markets: Public/Private Cloud Storage (Solution & Software) Market Forecasts & Opportunities, 2019
Research and Markets: LTE Market (Components, Technologies and Applications) Report 2012-2020
Research and Markets: Global Smart Cities Market (Home, Building Automation, Energy Management, Industrial Automation, Healthcare, Education, Water, Transportation, Security) Report 2014-2019
Research and Markets: Japan's Top 100 Consumer Markets 2014-2025
REG-First Trust Global Funds PLC Net Asset Value(s)
REG-First Trust Global Funds PLC Net Asset Value(s)
REG-First Trust Global Funds PLC Net Asset Value(s)
REG-First Trust Global Funds PLC Net Asset Value(s)
UPDATE 2-China's Ramu nickel mine in PNG restarts after attacks - embassy
BRIEF-China's Heilan Home expects surge in H1 profit after acquisition deal, restructuring
REFILE-Australia may ease immigration rules as it eyes Chinese millionaires
Australia may ease immigration rules as it eyes Chinese millionaires
Research and Markets: Global Power Electronics Market 2014-2020: Substrate Wafer Technology (GaN, SiC, and Others), Devices (Power IC, Power Module & Power Discrete)
Research and Markets: Global Human Identification Market Report 2014-2018: Technology, Application, DNA Amplification, Quantification, Extraction, Services, & Software Analysis
BRIEF-Beiersdorf CEO says markets are cooling down dramatically
Taiwan July export growth weaker than forecast
Simon Morris: Investment in Property Funds â The Safe Approach
Hong Kong shares end at 2-week low as Macau casinos tumble
Research and Markets: Global System in Package (SIP) Market Report 2014-2020: Technology, Type, Interconnection Technology & Applications Analysis
FOREX-Yen slips on pension fund stock shift; Aussie hit by data
Research and Markets: Global Cyber Security Market 2014 - Opportunities and Forecasts to 2018
More Chinese cities relax property rules in policy shift
Commerzbank Russia exposure covered by collateral, insurance - CFO
StanChart exec: banks treated like 'criminals' for anti-money laundering lapses
CEE MARKETS 1-Currencies extend losses on Ukraine, Hungarian bank pressures
Research and Markets: Global Printed Electronics Research Report 2014: Material (Substrates & Inks), Technology (Screen, Gravure, Inkjet & Flexography), Application (Displays, Sensors, OLEDs & PVs)
European shares slip again; eyes on ECB
Breakingviews: Euro zone debt
China Unicom H1 net income up 26 pct on strong 3G, 4G sales
BRIEF-Everbright Securities' July net profit at 126.5 mln yuan
Research and Markets: Japanese 3D Printer Market Report 2014-2018
UPDATE 2-Zurich says restructuring on track as profit rises
UPDATE 2-Commerzbank speeds up asset clear out, net profit doubles
BRIEF-Henan Taloph Pharma to acquire stakes in medicine firms for 516 mln yuan
REFILE-UPDATE 1-Moncler posts first-ever Q2 core profit as sales accelerate
BRIEF-China Southwest Securities' July net profit at 70.4 mln yuan
Research and Markets: Finishing Materials Market in USA: Business Report 2014
Exclusive: Japan's GPIF to boost stock allocation to over 20 percent - sources
DIARY - WEU EARNINGS Events - Part 3
Research and Markets: Global Health and Wellness Food Market 2014-2018: Vendors Dominating are Danone, General Mills, H.J. Heinz, Kellogg, Nestle & PepsiCo
MarketResearch.com Announces Distribution of Socintel360 Research
Corporate Social Responsibility Weekly Recap (July 30, 2014 â August 6, 2014)
ECB funding to Italian banks falls as more crisis loans repaid
RPT-UPDATE 1-Bottler Coca Cola HBC warns of "sudden deterioration" in Russian market
UPDATE 1-Taiwan July exports pick up on tech demand, but lag forecast
Research and Markets: Global Propionic Acid Market Forecasts and Opportunities, 2013 - 2019
China upholds death penalty for businessman linked to former security czar
Research and Markets: Internet of Things - Technology and Application Market Analysis 2014
Elbit Imaging Ltd. Announces Additional Updates to Annual General Meeting Proposals
BRIEF-Commerzbank not looking at issuing CoCo-bond in short term - CFO
Research and Markets: Construction Site Supplies Market in China: Business Report 2014
UPDATE 2-Cobham reassures on 2015 growth as defence cuts hit this yr
Beiersdorf CEO says does not see weakness in Russian market
Research and Markets: Over The Top (OTT) Market by Content, Access Type - Worldwide Forecasts & Analysis (2014 - 2019)
REG-Dimensional Fund Advisors Ltd. Form 8.3 - Carillion Plc - Ordinary shares
Research and Markets: Construction Site Supplies Market in Malaysia: Business Report 2014
Research and Markets: Finishing Materials Market in United Arab Emirates: Business Report 2014
Egyptian pound steady at c. bank sale, weaker on black market
BRIEF-India cbank says to conduct 610 bln rupees of 14-day term repo auction on Friday
China's latest anti-trust probes revive protectionism concerns
Deutsche Telekom wants help from regulators in US spectrum auction
Research and Markets: Global 4K Display Resolution Market Report 2014
U.S. Homeland Security contractor reports computer breach
Research and Markets: Oil and Gas Terminal Automation Market Report 2014 - Product, Transportation Mode & Geography Analysis
B Communications Reports its Financial Results for the Second Quarter of 2014
UPDATE 1-Cheung Kong Infra, Frasers get nod for multi-billion dollar Australia bids
REG-World Trust Fund Net Asset Value(s)<048326625X.LU>
Deutsche Telekom Q2 profit beats forecasts on U.S. growth
Deutsche Telekom wants help from regulators in U.S. spectrum auction
Internet Gold Reports its Financial Results for the Second Quarter of 2014
Boyden Global Executive Search Expands Technology Practice
BRIEF-UET United Electronic Technology Q2 consolidated revenues grew by 1.1 million EUR to 12.403 million EUR
UPDATE 2-Euronext accelerates cost cuts; CEO says job not in danger
Acer posts highest net profit since Q1 2013 amid PC turnaround
Manulife Financial reports 2Q14 net income of $943 million, core earnings of $701 million, a regulatory capital ratio of 243%, and a dividend increase of 19%
Mining Global Announces New Ticker Symbol, MNGG
Taminco Corporation Announces Second Quarter 2014 Results
Montclair State University Selects Cognizant to Transform Financial Management and Decision-Making to Support Growth
Financial Situation Improves for Small Businesses, Future Remains Uncertain
Quest Resource Holding Corporation to Present at Jefferies 2014 Global Industrials Conference
Higher One Holdings, Inc. Reports Second Quarter 2014 Financial Results
Research and Markets: Global Market Report of Racecadotril
EMERGING MARKETS-Russian bond yields surge on food bans as emerging currencies retreat
Research and Markets: Circuit Breakers and Fuses Market - Global Industry Analysis 2013 - 2019
Research and Markets: Finishing Materials Market in United Kingdom: Business Report 2014
China's latest anti-trust probes revive protectionism concerns
Research and Markets: Global Market Report of Sodium bisulfite
Research and Markets: Global Market Report of Carbon disulphide
Canada's BCE profit rises 6 pct
Lightstream Announces Funds Flow From Operations of $177 Million and Update to 2014 Guidance
Mitel Reports Second Quarter 2014 Financial Results
CECO Environmental Reports Second Quarter and Six Month 2014 Results
Horizon Pharma Reports Second Quarter 2014 Financial Results and Provides Business Update
Lightstream Announces Funds Flow From Operations of $177 Million and Update to 2014 Guidance
Synchronoss Technologies, Inc. Prices $200.0 Million of 0.75% Convertible Senior Notes Due 2019
Celladon Reports Second Quarter 2014 Financial Results and Recent Highlights
UPDATE 1-China Unicom earnings disappoint after value-added tax kicks in
Research and Markets: Power Generation: Global Group of Eight (G8) Industry Guide - Value and Volume 2009-13 and Forecast to 2018 for the $500+ Billion Industry
Research and Markets: Global Market Report of Dazomet
Research and Markets: Potassium Chloride Market - Global Industry Analysis 2013 - 2019 (Fertilizers, Pharmaceuticals, Industrial, Others)
BRIEF-China Sinomach Auto's H1 net profit down 3.6 pct y/y
Reach Energy's new shares for public oversubscribed
REG-Alliance Trust PLC : Net Asset Value(s)
CapMan's financial reporting in 2015
Manulife Financial net profit triples; company hikes dividend
BRIEF-Changjiang Securities' H1 net profit up 36.1 pct
Research and Markets: Global Market Report of Pentane
SE Asia Stocks - Range-bound amid foreign outflows
BRIEF-Beijing Ultrapower Software's H1 net profit down 18.2 pct
Euro zoneâs biggest problem is debt, not slow growth
EU mergers and takeovers (Aug 7)
FOREX-Yen slips on pension fund stock shift; eyes on ECB
Liquidity Services, Inc. Announces Third Quarter Fiscal Year 2014 Financial Results
Are too-big-to-fail banks being cut down to size?
Bank of England holds steady as rates debate heats up
HedgeCoVest Named as a Presenter at the National Finovate Fall Conference in New York
AngelList with Expansion VC Join $50 Million Series C Investment in Life360
RetailMeNot, Inc. Releases "The State of Digital Coupons" Study Showing How Digital Coupons Are Driving Mobile And Omni-Channel Sales
OGE Energy Corp. reports second quarter results
China Information Technology, Inc. Retains Grayling As Investor Relations Counsel
AmTrust Financial Services, Inc. Reports Strong Profit Growth for Second Quarter 2014 With Operating Earnings(1) Per Diluted Share Rising 78.7% to $1.34 and Net Income of $1.33 Per Diluted Share
EnteroMedics Reports Second Quarter 2014 Financial Results
Duke Energy posts strong second quarter 2014 results; increases outlook for 2014
AES Reports Second Quarter 2014 Adjusted Earnings Per Share of $0.28; Maintains 2014 Guidance
Command Center Reports Second Quarter 2014 Financial Results
13D Activist Fund Named Category King by The Wall Street Journal for The One Year Period Ending July 31, 2014
Sterling Trader Announces Full Featured Canadian Market Access
REMINDER/Media Advisory: Industry Minister Moore to Announce Support for New Space Technology
Bank of England holds steady as rates debate heats up
Keryx Biopharmaceuticals, Inc. Announces Second Quarter and Six Month 2014 Financial Results
UPDATE 2-RSA bounces back to profit, boosts reserves again
National General Holdings Corp. Reports Second Quarter 2014 Results
Fifth Street Finance Corp. Announces Quarter Ended June 30, 2014 Financial Results
Scripps Networks Interactive Reports Second Quarter Financial Results
REG-First Trust Portfolios Form 8.3 - Carillion plc
Research and Markets: Global Market Report of Copper oxychloride
UPDATE 1-Canada's BCE profit grows 6 pct; affirms 2014 outlook
TABLE-Russian gold/fx reserves fall to $468.4 bln
NetDragon Websoft Inc. to Report 2014 Interim Financial Results on August 22, 2014<0777.HK>
Research and Markets: Hospital Stretchers Market - Global Industry Analysis 2014-2019
Duke Energy profit rises on strong regulated utility business
REG-New City Energy Ltd : Net Asset Value(s)
Research and Markets: Global Market Report of 1,12-DODECANEDIOIC-D20 ACID
UPDATE 2-Munich Re's profits rise despite jump in claims
CANADA STOCKS-TSX set to open higher
NRG Energy, Inc. Reports Second Quarter Results; Completed First NRG Yield Drop Down and Announces Formation of NRG Home and NRG Renew
Nautilus Minerals Announces Financial Results for Q2 2014
Nautilus Minerals Announces Financial Results for Q2 2014
China's latest anti-trust probes revive protectionism concerns
Research and Markets: Global Market Report of Ethylene carbonate
Regency Energy Partners and American Energy - Midstream, LLC Enter Into Joint Venture
Entertainment Gaming Asia Inc. Reports Second Quarter 2014 Results And Provides Market Update
NorthStar Realty Finance Announces Second Quarter 2014 Results
Ebix Board Declares Quarterly Dividend of 7.5 Cents Per Share
Compressco Partners, L.P. Announces Second Quarter 2014 Results Including 97% Increase In Net Income
NRG Yield, Inc. Reports Second Quarter 2014 Financial Results, Completes First ROFO Acquisition, Closes Green Bond and Equity Offerings, and Raises Quarterly Dividend by 4.3%
Apollo Investment Corporation Reports Financial Results for the Quarter Ended June 30, 2014
Regency Energy Partners and American Energy â Midstream, LLC Enter Into Joint Venture
Derma Sciences Reports Second Quarter Financial Results
Intercontinental Exchange Reports Second Quarter 2014 Results
GTx Announces Webcast of Corporate Presentation at the 2014 Wedbush Pacgrow Life Sciences Management Access Conference
Sarepta Therapeutics Announces Second Quarter 2014 Financial Results and Recent Corporate Developments
Intercontinental Exchange Declares Quarterly Dividend of $0.65 Per Share
NxStage Reports Record Second Quarter 2014 Financial Results And Increases Full-Year Revenue Guidance
Fannie Mae says will give U.S. Treasury $3.7 billion
Advanced Photonix to Webcast Fiscal 2015 First Quarter Earnings
India Advantage Fund Ltd : Net Asset Value
Intercontinental Exchange Acquires Trading Technology Patents
Goldman Sachs says alternative trading system being investigated
UPDATE 1-Canada's Telus posts 33 percent jump in quarterly profit
BRIEF-Leshi Internet Info & Tech to raise 4.5 bln yuan in private placement
Recognized energy industry leader joins VisiQuate; adds domain expertise
ECB holds rates, waits for new funding measures to kick in
UPDATE 2-SMA Solar warns of price pressure after 7th straight quarterly loss
500.com Limited Enters Into Strategic Partnership with China Mobile Limited
BRIEF-Ingenious Ene-Carbon to raise up to 688.5 mln yuan in private placement
ICE reports higher second-quarter earnings
BCE reports second quarter 2014 results



---
**Búsqueda filtrada 2**

In [26]:
query = "financial losses"

metadata_filter = {
    "label": "Fall"
}

print(f"{R}Consulta:{E}", query)#⚠️

print(f"{A}Filtro:{E}", metadata_filter)

results = filtered_vector_store.search(
    query=query,
    metadata_filter=metadata_filter
)

mostrar_resultados(results)

Consulta: financial losses
Filtro: {'label': 'Fall'}
==============================
Resultado #1
Score: 0.4020
Texto:
Two Firms Enter Clean-Air Settlement
Tullow's CEO to Meet with Uganda's President
Aldi Faces Suit From Store Managers
Foreign Buyers Snap Up Japanese Shares
Bloomies to Open Outlet Stores
BSkyB Loses Appeal Over ITV Stake
Weaker Yen Lifts Japan Shares
U.S. Sales Boost Ahold's Revenue
Fifth Third Bancorp's Loss Shrinks
Indian Shares End 2.4% Lower
N.Y. Times to Charge for Web
AXA Unit Raises Profit Estimate
Falling Beer Sales Pressure Brewers
Paris Urges Areva, EDF to End Spat
Cockpit-Door Defects Worry Officials
Dubai World Loses Top Executive
Global Jitters Boost Dollar
LaBranche Realigns After Specialist Sale
Icahn Wins Bid for Fontainebleau
GenRe Reaches Deal in AIG Case
Metadatos:
  - id: nifty_8
  - date: 2010-01-21 00:00:00
  - context: date,open,high,low,close,adj_close,volume,pct_change,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma
  - label: Fall
  - pct_change: -0.0223

==============================
Resultado #2
Score: 0.3535
Texto:
S&P Cuts Ratings On Italian Banks
Boeing Loses Three Freighter Orders
Bed Bath's Profit Rises 26%
Terra Nitrogen, Kips Bay Medical: Biggest Price Decliners (TNH, KIPS)
Hewlett-Packard, Flamel Technologies: Biggest Price Gainers (HPQ, FLML)
Oil Tumbles After Fed News
Range Resources, Shell Not in Talks
Gold Pulls Back on Fed Plan
AMR, United See Solid Revenue Growth
Pacific Rubiales Moves to Restart Colombia Oil Output
Tesco to Float $472 Million Thai Property Fund
Alpha Natural Resources, Kips Bay Medical: Biggest Price Decliners (ANR, KIPS)
GMX Resources, Farmer Bros.: Biggest Price Gainers (GMXR, FARM)
Vanguard MSCI Emerging Markets, Apple: Money Flow Leaders (VWO, AAPL)
More Qantas Strikes Are Possible
Mediobanca Slips To Net Loss On Write-Downs
French Regulator Targets Canal Plus
Costs Nip General Mills
Error Causes Slump In Dollar Vs. Swiss Franc
U.S. Treasury to Sell Warrants for SunTrust Banks
French Bankers Reject Solvency Fears
Indian Shares End Lower
UBS Board to Meet in Singapore Ahead of F1
Asia Rises Before Fed Meeting
Boeing in Talks with Chinese Airlines on Dreamliners
Hynix Creditors Seek New Bids for Hynix Stake
ING Cuts Italian Debt Holdings
China Studies Foreign IPOs
Boeing, Chinese Supplier Set to Extend Pact
Banks Shun Riskier Buyouts
UBS Board to Focus on Postscandal Plan
Airline Profits Hit the Brakes
Air Force Revises Unpopular Flight Plan in West
Raid at Gibson Guitar Strikes Sour Note
GE Sees Bright Spot in Energy Unit
Most CD Yields Drift Lower
No Joy in Holiday Retail Forecast
Focus on Goldman Ex-Director
Summer of Discontent Sends DAX Down
SEC Watchdog Requests Probe
Covered Bonds Take Cover
United Technologies Is Near Deal for Goodrich
Solyndra Executives to Plead the Fifth
Europe Shares Rise on Greece Hope; Japan Falls
Miner New Hope Is Open to a Sale
European Stocks Rise
Dollar Treads Water With Focus on the Fed
Swap Setback for UBS, BNP Paribas
Lufthansa Cuts Earnings Outlook
Lloyds Readies Property Loan Sale
ConAgra's Earnings Take Hit From Costs
Banker Says Euro Zone Will Avoid Double Dip
IATA Sees Higher 2011 Airline Profit
Community Banks Fight Large Bank Mergers
Oracle Displays Resilience
Home Forecast Calls for Pain
Steel Users Seek Futures
GOP Leaders Urge Fed Not to Take Action
Colombia Protests Halt Oil Output at Big Fields
SEC Pushes Stock-Audit System
Metadatos:
  - id: nifty_341
  - date: 2011-09-21 00:00:00
  - context: date,open,high,low,close,adj_close,volume,pct_change,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma
  - label: Fall
  - pct_change: -0.0323



---
**Búsqueda filtrada 3**

In [27]:
query = "stable market"

metadata_filter = {
    "label": "Neutral"
}

print(f"{R}Consulta:{E}", query)#⚠️

print(f"{A}Filtro:{E}", metadata_filter)

results = filtered_vector_store.search(
    query=query,
    metadata_filter=metadata_filter
)

mostrar_resultados(results)

Consulta: stable market
Filtro: {'label': 'Neutral'}
==============================
Resultado #1
Score: 0.4373
Texto:
This Holiday Season, Shoppers Find It More Invasive to be Targeted In-Store than Online
Consider Canada City Alliance Representing 59% of Canadian GDP Delivers Infrastructure Opportunity Message on CETA During Three-City European Investment Mission
ECB's Noyer: financial markets stabilising, rates returning to normal
ECB's Noyer: financial markets stabilizing, rates returning to normal
Sasol Chief Financial Officer Update
Australia shares edge higher on Wall St, banks, weak $A underpin
FOREX -Yen skids to 6-month low vs dollar, 4-year low vs euro
UPDATE 1-China Everbright Bank says profit, NPLs up ahead of HK listing
BOJ's Kuroda: Impact of negative rates on economy unknown
BOJ's Kuroda: Impact of negative rates on economy unknown
PRESS DIGEST- New York Times business news - Nov 25
PRESS DIGEST - Wall Street Journal - Nov 25
Polarcus Financial Calendar 2014
China reaffirms ban on housing sales on rural land - media
China reaffirms ban on housing sales on rural land: media
Signal dâalarme! 3 French stocks to avoid â StarMine
GLOBAL MARKETS-Iran deal saps oil prices, cheers Asia shares
SE Asia Stocks-Most up; Thai stocks fall as political protests escalate
BOUSSARD AND GAVAUDAN HOLDING LIMITED (GBP) - Net Asset Value(s)
Market Chatter- Corporate finance press digest
China to launch two new carbon trading exchanges
Apple acquires Israel's PrimeSense in a $350 mln deal - Bloomberg
REG-Tern Plc : First Investment
REG-Espirito Santo Fin Issue of Debt
Update-Moody's: Japan automakers profit rebound, but weaker than peers
China shares fall, Sinopec sinks after pipeline explosion
Update-Moody's: Belgium's banking system outlook changed to stable from negative
TABLE-Foreign trading in South Korean stocks
Faurecia details transformation strategy for profitable growth and cash generation
TABLE-Indian banks' refinancing with RBI rises to 416.64 bln rupees - cbank
PRECIOUS-Gold drops 1 percent as equities gain after Iran deal
ECB's Noyer: Rates must remain low, could go lower if needed
REFILE-RESEARCH ALERT-Eqstra: BPI Equity Research cuts target price
Songa Offshore SE: Extensive recapitalization plan including USD 425 million in new equity and convertible bonds
BRIEF-China's Guidong Electric subscribes to 372.84 mln yuan worth of Sealand's share placement
CORRECTED-Technical signs, rising risk appetite, drive yen selling fever
BRIEF-China Merchants Securities to issue up to 4 bln yuan worth of asset-backed securities
Kapow Earns Spot on Analyst One Top Technologies List
Reuters Today: Iran nuclear deal: now the hard part starts
BRIEF-China Fortune Land's units win land auctions totalling 690.9 mln yuan
REG-First Trust Global Funds PLC Net Asset Value(s)
REG-First Trust Global Funds PLC Net Asset Value(s)
REG-First Trust Global Funds PLC Net Asset Value(s)
RPT-Fitch rates Xinyuan Real Estate's proposed USD notes 'B+(EXP)'
Hong Kong shares end down, Tencent strength offsets Sinopec
RPT-Fitch: China Developers' LAT payables not a concern
Taiwan to allow Chinese firms to issue yuan bonds - sources
Chrysler IPO could raise $1.5 billion-$2 billion: WSJ
Bunds edge up as Iran deal adds to worries about low euro zone inflation
DIARY -  Western European Non-Earnings events from Nov 25
Research and Markets: Mild Cognitive Impairment - Pipeline Review, H2 2013
BRIEF-China's Jinke wins auction totalling 322.8 mln yuan for two residential sites in Chongqing
China security boss urges judicial independence, transparency
DIARY - Western European Corporate events from Nov 25
TrustBuddy on Track to Meet the Expected Additional 400M SEK P2P Lending Capital
UPDATE 1-Seadrill lifts dividend, shrugs off slower oil firm spending
SNAPSHOT-India stocks, bonds, rupee, swaps, call at 0843 GMT
Research and Markets: MVNO Business Plan - Market Research
Demand for Consumer Debt Continues to Grow Moderately While the National 90 Day-Plus Delinquency Rate at Record Lows-Equifax Canada Reports
BRIEF-China's Sealand Securities places 518 mln shares totalling 3.3 bln yuan
Demand for Consumer Debt Continues to Grow Moderately While the National 90 Day-Plus Delinquency Rate at Record Lows-Equifax Canada Reports
Fiserv Releases TradeFlow for Linux to Help Greater Number of Financial Institutions Reduce Cost of Post-Trade Processing
Draghi did not block proposals on govt debt risk-weighting - ECB
How ICT will change next generation working life
RPT-Fitch: Sovereign risks persist for Italian insurers amid weak non-life growth; life sales volatile
Research and Markets: Electricity Industry Market Report 2013
Dubai to act as hub for emerging Islamic markets -IDB
FOREX-Yen drops to 6-month low versus dollar, 4-year low vs euro
Research and Markets: Psychiatric Disorders - Pipeline Review, H2 2013
ASIA CREDIT CLOSE: Market stays solid in thin trading
How ICT will change next generation working life
Research and Markets: Bancassurance in Europe to 2020: Market Profile
UPDATE 2-Cinda IPO unveils secrets of a Chinese bad debt factory
Research and Markets: General Chemicals Markets in China Part I (Choice of Any 5 Full Research Reports from Our 200 Chemical Report Collection)
China's 'Mr. Market' says reform the 'only way out'
Research and Markets: Global and Chinese Gas-to-Liquid (GTL) Industry Report 2013
UPDATE 1-China to launch two new carbon trading exchanges
China to launch two new carbon trading exchanges
Research and Markets: Nuclear Export - A Challenging Time for France to Attract Emerging Nuclear Countries
FACTBOX-Iran's oil fund stash in Asia
Research and Markets: Research Report: Booming Used Car Market in India Outlook 2017
Perfect World Announces Recent Business Developments
TABLE-Offshore investors sell South African stocks and bonds
j2 to Participate in Two December 2013 Investor Conferences
KababayanKo.com of Alpha Network Alliance Ventures Inc. Moves Into the Heart of the Philippines
Mint Announces Financing
DaVita HealthCare Partners Inc. Comments on the Final CMS ESRD Rates and Provides Initial 2014 Operating Income Guidance
Research and Markets: Rubber Products Markets in China (6 Full Research Reports Collection)
Research and Markets: Annually Updated Market Data: Producer of Corn Starch in China
SouthGobi Resources Provides First Bi-Weekly Update on Restated Financials
Research and Markets: 2013 China Broadcast Pro Video Marketpalce Trends Report
SouthGobi Resources Provides First Bi-Weekly Update on Restated Financials
Research and Markets: US Leading the Charge in Small Modular Reactor Development
Research and Markets: Machinery and Equipment Markets in China (6 Full Research Reports Collection)
Research and Markets: Automobile and Automotive Component Markets in China (6 Full Research Reports Collection)
DIARY-S&P; 500 EARNINGS WEEK AHEAD
DIARY-S&P; 500 EARNINGS MONTH AHEAD
Research and Markets: Global and Chinese Polybutene (PB) Industry Report 2013
BRIEF-China's Zhongyin Cashmere gets regulatory approval for private placement of new shares
Research and Markets: 2013 Outsourcing Guide for the Chemicals Industry
Euribor rates rise on scaled down expectations of imminent ECB action
Research and Markets: Research Report: Brunei Darussalam Gas Markets, 2013
Research and Markets: Consumer Automotive Financial Services in Romania
REG-db x-trackers Stoxx Europe 600 Basic Resources Short Daily ETF Net Asset Value(s)
REG-db x-trackers MSCI WORLD ENERGY TRN INDEX ETF Net Asset Value(s)
Research and Markets: Bancassurance in the Americas to 2020: Market Profile
REG-db x-trackers MSCI WORLD INDUSTRIALS TRN INDEX ETF Net Asset Value(s)
REG-db x-trackers STOXX Europe 600 Industrial Goods Short Daily ETF Net Asset Value(s)
REG-db x-trackers MSCI WORLD MATERIALS TRN INDEX ETF Net Asset Value(s)
REG-db x-trackers FTSE 100 Short Daily ETF Net Asset Value(s)
REG-db x - trackers S&P; 500 2x Inverse Daily ETF Net Asset Value(s)
REG-db x-trackers MSCI Mexico Net Asset Value(s)
REG-db x-trackers S&P; 500 Inverse Daily ETF Net Asset Value(s)
Research and Markets: Emergency Management and Incident Market: Forecasts and Analysis (2013 - 2018)
Research and Markets: Virtual Tour: Auchan (India)
REG-db x-trackers MSCI Indonesia TRN Index ETF Net Asset Value(s)<047628962X.LU>
REG-db x-trackers FTSE/EPRA NAREIT DEVELOPED EUROPE REAL ESTATE ETF Net Asset Value(s)
REG-db x-trackers MSCI ASIA EX JAPAN TRN INDEX ETF Net Asset Value(s)
REG-db x-trackers II iBoxx Â£ Gilts Total Return Index ETF Net Asset Value(s)<032146406X.LU>
REG-db x-trackers US DOLLAR CASH ETF Net Asset Value(s)
REG-db x-trackers MSCI PACIFIC EX JAPAN TRN INDEX ETF Net Asset Value(s)
REG-db x-trackers II iBoxx $ Treasuries Total Return Index ETF Net Asset Value(s)<042945935X.LU>
REG-db x-trackers MSCI Russia 25% capped Index ETF Net Asset Value(s)
REG-db x-trackers II iBoxx $ Treasuries 1-3 Total Return Index ETF Net Asset Value(s)<042945889X.LU>
REG-db x-trackers FTSE Vietnam ETF Net Asset Value(s)
Research and Markets: Geographic, Technological, and Financial Portfolio Analysis of Top 30 Fastest-Growing Automotive Suppliers
Research and Markets: Global Motor Vehicle Part Market to 2017
REG-DB X-Trackers - MSCI EMERGING MARKETS TRN INDEX ETF Net Asset Value(s)
UPDATE 1-Norway's 2014 oil investment plan may be too optimistic
REG-DB X-Trackers - MSCI EM ASIA TRN INDEX ETF Net Asset Value(s)
NICB Reports Small Decline in Motorcycle Thefts in 2012
Century 21 China Real Estate Announces Results of Annual General Meeting
TransUnion: Auto Loan Delinquencies Rise on Both Quarterly and Yearly Basis
Suroco Energy Inc. Announces Filing of Third Quarter Financial Statements and MD&A;
Research and Markets: China Nd-Fe-B Permanent Magnetic Material Industry Report 2013
REG-DB X-Trackers - MSCI TAIWAN TRN INDEX ETF Net Asset Value(s)
Research and Markets: Australia and New Zealand SCADA Market
British crowdfunding site to allow cross-border investment
Turkey's Yapi Kredi to borrow $500 mln in 5-yr eurobond -bankers
British crowdfunding site to allow cross-border investment
REG-DB X-Trackers - EURO STOXX 50 SHORT DAILY ETF Net Asset Value(s)
REG-DB X-Trackers - MSCI BRAZIL TRN INDEX ETF Net Asset Value(s)
Research and Markets: Chinese Markets for Epoxy Resin 2013
REG-db x-trackers MSCI Emerging Market Short Daily ETF Net Asset Value(s)
REG-DB X-Trackers - S&P; CNX NIFTY ETF Net Asset Value(s)
New Issue-Guocoland prices SG$125 mln 2016 bond
REG-db x-trackers MSCI WORLD CONSUMER DISCRETIONARY TRN INDEX ETF Net Asset Value(s)
Russia's Sistema Q3 earnings boosted by Russneft stake sale
REG-DB X-Trackers - MSCI KOREA TRN ETF Net Asset Value(s)
REG-db x-trackers MSCI WORLD CONSUMER STAPLES TRN INDEX ETF Net Asset Value(s)
REG-DB X-Trackers - FTSE/XINHUA CHINA 25 ETF Net Asset Value(s)
REG-db x-trackers MSCI WORLD FINANCIAL TRN INDEX ETF Net Asset Value(s)
Fitch: Latest MMF Snapshot Provides End-October Money Market Fund Analytics
Alma Media's long-term financial targets
REG-db x-trackers MSCI WORLD HEALTH CARE TRN INDEX ETF Net Asset Value(s)
REG-db x-trackers MSCI WORLD INFORMATION TECHNOLOGY TRN INDEX ETF Net Asset Value(s)
REG-db x-trackers STOXX GLOBAL SELECT DIVIDEND 100 ETF Net Asset Value(s)
REG-db x-trackers STOXX EUROPE 600@ Banks Short Daily ETF Net Asset Value(s)
REG-db x-trackers MSCI WORLD TELECOMMUNICATION SERVICES TRN INDEX ETF Net Asset Value(s)
Research and Markets: GCC Industrial Water and Wastewater Treatment Chemicals Market
REG-db x-trackers MSCI WORLD UTILITIES TRN INDEX ETF Net Asset Value(s)
REG-db x-trackers STOXX@ EUROPE 600 Health Care Short Daily ETF Net Asset Value(s)
Polarisâ Intellect Financial Advisor Business eXchange Rated a âBest in Classâ Solution for Enterprise Support
REG-db x-trackers Short STOXX@ Europe 600 Oil & Gas Short Daily ETF Net Asset Value(s)
REG-DB X-Trackers STOXX EUROPE 600 BASIC RESOURCES ETF Net Asset Value(s)
REG-DB X-Trackers STOXX EUROPE 600 OIL & GAS ETF Net Asset Value(s)
REG-db x-trackers S&P; EUROPE 350 SHARIAH ETF Net Asset Value(s)
REG-db x-trackers S&P; JAPAN 500 SHARIAH ETF Net Asset Value(s)
Research and Markets: Chinese Markets for Amino Resin 2013
REG-DB X-Trackers STOXX EUROPE 600 HEALTH CARE ETF Net Asset Value(s)
REG-DB X-Trackers STOXX EUROPE 600 BANKS ETF Net Asset Value(s)
REG-DB X-Trackers - STOXX EUROPE 600 TELECOMMUNICATIONS ETF Net Asset Value(s)
REG-db x-trackers S&P; 500 SHARIAH ETF Net Asset Value(s)
Research and Markets: Cloud in European Vertical Markets
REG-DB X-Trackers - STOXX EUROPE 600 TECHNOLOGY ETF Net Asset Value(s)
REG-db x-trackers DOW JONES ISLAMIC MARKET TITANS 100 ETF Net Asset Value(s)
REG-db x-trackers STOXX EUROPE 600 ETF Net Asset Value(s)
What Awaits the Future of Travel?
REG-db x-trackers S&P; Global Infrastructure ETF Net Asset Value(s)
EMERGING MARKETS-Turkey, India lead gains after Iran deal
UPDATE 1-Russia's Sistema earnings boosted by Russneft stake sale
Research and Markets: Indian Market for Membrane Modules
REG-Alliance Trust PLC : Net Asset Value(s)
RPT-Fitch: Ghana budget fiscal aims limited, overshoots still likely
REG-World Trust Fund Net Asset Value(s)<048326625X.LU>
Research and Markets: Lighting Market - UK 2010-2014
Research and Markets: Assessment of the China Tourism Market
REG-DB X-Trackers - STOXX EUROPE 600 UTILITIES ETF Net Asset Value(s)
FOREX-Yen falls versus dollar and euro as Iran deal lifts stocks
TechFaith Reports Third Quarter 2013 Financial Results
RetailMeNot Shoppers Trend Report: One in Four Consumers Plan to Spend at Least Half of Their Workday Shopping Online on Cyber Monday
Research and Markets: China Spectacles Industry Report, 2013-2015
Research and Markets: DIY Multiples Market - UK 2010-2014
SNAPSHOT-India stocks, bonds, rupee, swaps, call at close
Novadaq to Present at December Investor Healthcare Events
Kratos Discontinues Proposed Refinancing Effort
Mitek Enabled Photo Capture Bill Pay Named a Top Innovator of 2013 by American Banker
Camelot Information Systems Inc. Announces Unaudited Third Quarter 2013 Financial Results
NVIDIA to Offer $1.3 Billion of Convertible Senior Notes
NewSat Ltd. Begins Trading on OTCQXÂ®
Investors Will Reach For New Active Strategies, Far More Than Passive, During Next Five Years: Casey Quirk
Highpower International Announces Its Patent Portfolio Now Exceeds 100
Santa Maria Petroleum Inc. Disposes of Its Participation Interest in the Investments, Income and Revenues of the LLANOS 27 Project in the Llanos Basin in Colombia
REG-DB X-Trackers - STOXX EUROPE 600 INSURANCE ETF Net Asset Value(s)
REG-db x-trackers DB HEDGE FUND INDEX ETF SHARECLASS 3C Net Asset Value(s)
The Radicati Group Releases "Enterprise Mobility Management Market, 2013-2017"
Businesses Stretching their Budget with Pre-Owned and Refurbished Computer Equipment from BBC Technology Solutions
Santa Maria Petroleum Inc. Disposes of Its Participation Interest in the Investments, Income and Revenues of the LLANOS 27 Project in the Llanos Basin in Colombia
Penn National Gaming Names Saul V. Reibstein Chief Financial Officer
Novadaq to Present at December Investor Healthcare Events
Xcel Energy to Host New York Investor Meeting December 4
Bankrupt U.S. city to dispute debt with California pension fund
AECOM publishes first corporate safety, health and environment report âSafety for Life.â
Bankrupt U.S. city to dispute debt with California pension fund
Analysis: Fund managers find Fairway's mix to their taste
Launch of "StockViews Campus" Provides a New Resource for Investors
CBD Marketing Debuts "Words of Wisdom from Kick-Ass Women" e-Book
Research and Markets: European Rack and Rack Options Market
Bunds rise as Iran deal fuels speculation ECB may ease further
Research and Markets: A Merchant's Guide to Credit and Loyalty - EMEA
UPDATE 1-Essar Energy's profit dented by higher costs, weak Indian rupee
US STOCKS-Futures point to continued rally, but oil price dips
European stocks head towards five-year high after Iran nuclear deal
Research and Markets: Printed Electronics for Healthcare, Cosmetics and Pharmaceuticals 2014-2024
Detour Gold Announces Management Changes
Detour Gold Announces Management Changes
REG-Miscellaneous: Portfolio update and proposed tender offer
WesternZagros Announces Upcoming Investor Events
China's National Development and Reform Commission Notifies Qualcomm of Investigation
C&J; Energy Services to Present at the Cowen and Company Oil Services and E&P; Conference
WesternZagros Announces Upcoming Investor Events
Research and Markets: Future of Russia Oil Refinery Markets to 2020
Research and Markets: Italy Oil and Gas Markets Outlook to 2025
REG-DB X-TRACKERS MSCI WORLD TRN INDEX ETF Net Asset Value(s)
Investcorp acquires multi-family properties in greater Chicago, Austin, and Las Vegas valued at $270 million
RPT-Fitch publishes sovereign rating history
REG-DB x-trackers MSCI JAPAN TRN INDEX ETF Net Asset Value(s)
REG-db x-trackers EURO STOXX50 ETF Net Asset Value(s)
REG-DB X-Trackers - STOXX EUROPE 600 FOOD & BEVERAGE ETF Net Asset Value(s)
US STOCKS-Futures point to continued rally, but oil dips
Research and Markets: Global Epigenetics Drugs And Diagnostic Technologies Market Report 2013 - 2018
REG-DB X-Trackers - STOXX EUROPE 600 INDUSTRIAL GOODS ETF Net Asset Value(s)
GLOBAL MARKETS-Iran deal sends oil lower, lifts shares and dollar
Navios Maritime Holdings Inc. Reports Financial Results for the Third Quarter and Nine Months Ended September 30, 2013
Czech Asset Management, L.P. Raises $1.5 Billion Fund II - Its Second $1.0 Billion+ Direct Lending Fund In 34 Months
REG-db x-trackers EURO STOXX 50 INDEX ETF 1C Net Asset Value(s)
Research and Markets: Future of Nigeria Oil Refinery Markets to 2020
RPT-Fitch upgrades Sandnes Sparebank Boligkreditt's covered bonds to 'AA'; outlook stable
China to auction off illegally built official buildings - state media
Qualcomm says China's price regulator probing company
Early Morning Insight: Western Refining Inc., Plains GP Holdings L.P., Alon USA Energy Inc., and NuStar Energy L.P.
Italy's banks hope for capital boost from cenbank stakes in 2013
Early Briefing and Review: NQ Mobile Inc., Salesforce.com, LifeLock Inc., and Synaptics Inc.
India Advantage Fund Limited: Net Asset Value as at 22 November 2013
Early Briefing and Review: CA Inc., United Microelectronics Corp., China Unicom (Hong Kong) Ltd, and Methode Electronics Inc.
Legal Judgments, Stock Price Movements, Relief Aids, New Appointments, and Strategic Acquisitions - Research Report on Tiffany, Bed Bath & Beyond, Lumber Liquidators, Sotheby's, and Signet
Pre-Market Analysis: Vale S.A., Alpha Natural Resources Inc., Molycorp Inc., and Arch Coal Inc.
New Partnerships, Content Licensing Agreements, Omni-Channel Strategies, and Quarterly Financial Results - Research Report on eBay, Amazon, Limited Brands, Dick's Sporting Goods, and Gap
Stock Price Update, and Prestigious Accolades - Research Report on Freeport-McMoRan, United States Steel, Southern Copper, Steel Dynamics, and Gerdau
Housing Programs, Conference Schedules, Senior Secured Financing, Increased Home Values, and Stock Price Movements - Research Report on Wells Fargo, KeyCorp, PNC, First Republic, and SunTrust Banks
Upcoming Webinars, FDA Clearances, Preclinical Data Presentations, Completed Acquisitions and Financial Results - Research Report on Teva, Boston Scientific, Alnylam, Wright Medical, and Onconova
Stock Price Update, Advanced Technologies, Product Launches and Conferences Presentations - Research Report on Advanced Energy, Marketo, Fortinet, AVG Technologies, and BroadSoft
Product Upgrade, Board Changes, New Products, Stock Movements, and Dividends - Research Report on Tesla, Johnson Controls, BorgWarner, WABCO, and Lear
U.S. stock processor to roll out warning tool for trade errors
FDA Approvals, Public Offerings and Stock Price Movements - Research Report on BioMarin, AEterna Zentaris, Charles River, Anika Therapeutics and Halozyme Therapeutics



---
**Búsqueda filtrada 4**

In [28]:
query = "company profits"

metadata_filter = {
    "label": "Rise"
}

print(f"{R}Consulta:{E}", query)#⚠️

print(f"{A}Filtro:{E}", metadata_filter)

results = filtered_vector_store.search(
    query=query,
    metadata_filter=metadata_filter
)

mostrar_resultados(results)

Consulta: company profits
Filtro: {'label': 'Rise'}
==============================
Resultado #1
Score: 0.4019
Texto:
After Financial Crisis, Goldman  Goes It Alone
Tesla’s Loss Widens as Deliveries Fall Short
Waldorf Astoria Hotel Sale Completed
Euro Turns Higher on Reports of Greece Agreement
Whole Foods Profit Rises 5.7%
Pilgrim’s Pride Profit Up 17%
W.R. Grace: The End of an Empire
An Opportunity Opens for NBC Rivals
Corporate Watch: News Digest
Sysco, FTC Meet About US Foods Deal
Cheesecake Factory Profit Falls on Higher Costs
USA Today Pages to Appear in Other Papers
SEC Probes CVR Disclosure During Takeover
Hedge Funds Get Big Payoff on Currencies
Sun Life Financial Misses Analysts’ Expectations
Edict by Beijing Spells Trouble for Bonds
GE to Allow Proxy Access for Big Investors
Former Petrobras CEO Weighs In on Corruption Probe
Panera Bread’s Profit Falls 11%
Zulily Sees First-Quarter Sales Below Analyst Views
Kraft’s Shares Look a Bit Overcooked
Mondelez Profit Hit By Currency Effects, Higher Costs
MetLife’s Operating Income Edges Up
Boeing Can’t Make Case for Revamping 757 Jet
Home-Price Growth Picks Up Speed
TripAdvisor’s Fourth-Quarter Profit Soars
Asian Morning Briefing: U.S. Stocks End Flat
Pier 1’s Race to Build Online Business Takes a Toll
NetApp Shares Fall on Outlook
UPS Raises Dividend
Nvidia Profit Rises 31%
Applied Materials Offers Disappointing Forecast After Profit Jumps 38%
Oil Prices Slide
FXCM’s Retail Trading Volume Surged in January
Carlyle Caps a Strong Year Despite Drop for Quarter
Former Korean Air Executive Faces Judgment Over ‘Nut Rage’ Incident
Petrobras Platform Blast Leaves 3 Dead
Fonterra Makes Offer For Stake In Beingmate Baby
Zoetis Profit Up 20%, 2015 Outlook Cut Slightly
Merrill Lures $1.2B Team From Morgan Stanley
Italy’s Banca Monte Posts 11th Straight Quarterly Loss
Trump Taj Mahal Settles Over Anti-Money-Laundering Violations
Gold Falls as Stronger Dollar Weighs on Price
Blackstone to Buy Stake in New York Office Portfolio
CFTC Reviews Forex Rules
Revel Casino Deal Imperiled as Judge Denies Extension
Spanish Airport Operator’s Shares Soar in Market Debut
TransCanada Rebuts EPA Comments on Keystone
U.S. Budget Deficit Widens
Nigerian Central Bank Governor Says Naira at Appropriate Level
FBI to Probe Tax Filings
Brazil Retail Sales Post Worst Decline in 14 Years
Time Warner Reports Revenue Decline
Peltz’s Firm, DuPont Trade Salvos
As Oil Price Drops, Texas Lenders Watch for Fallout
A Gender Gap in Real Estate
Raymond James Drops Clawback Plan
PepsiCo Earnings, Revenue Decline
UniCredit’s Capital Position Hit by Russia
American Discloses Routes for New 787s
AOL Earnings Beat on Advertising Growth
Decline in Military Spending Set to Resume
Canadian Pacific Railway Gets Strike Notice
FCC Taps Banker to Aid Broadcast Auction
Test-Driving a Roth Conversion Technique
Aramark Warns of Potential Currency Headwinds
Intrepid Few Continue Trading in Greece
Malone Joins Lions Gate’s Board
Some Advisers Turn to Hedged-Equity Strategies
DDR Names David Oakes as CEO
Kinross Gold Shelves West African Mine Expansion
Glencore Plans Lonmin Exit
Banco do Brasil Forecasts a Fall in Loan Growth
Lorillard Sales Rise on Higher Pricing
KB Home Sees 25% Growth in New-Home Orders
Wal-Mart Plans $270.1 Million Canada Expansion
India to Sell Stakes in Five Firms
Penske Automotive Profit Rose 21% on Strong Demand
Rite Aid to Buy EnvisionRx for $2 Billion
India Considering Financial Incentives for Sugar Exports
Mosaic Earnings Soar on Higher Demand and Pricing
Thomson Reuters Swings to Profit
Air Canada Quarterly Loss Widens
Target Ends Online Movie Rentals
Markets Lower Ahead of Greece Talks
Computer Sciences to Restate Results
WellCare Earnings Drop on Severe Flu Season
Hilton to Buy Five Hotels
Tullow Suspends Dividend Amid Oil Rout
U.S. Firms in China See Rising Anti-Foreign Sentiment
Australian Stocks Lower Over Oil
Heineken Sweetens Dividend
Reckitt Benckiser Cuts Costs
ING Resumes Dividend
Commonwealth Bank Bemoans Political Uncertainty
Corporate Watch: News Digest
CSL Shaves Guidance as Competition Heats Up
U.K. Widens Tax-Evasion Probe
Drilling Slows as Oil Price Drops
Metadatos:
  - id: nifty_1004
  - date: 2015-02-11 00:00:00
  - context: date,open,high,low,close,adj_close,volume,pct_change,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma
  - label: Rise
  - pct_change: 0.0096

==============================
Resultado #2
Score: 0.3908
Texto:
Corporate Watch
Smartphone Woes Hurt Nokia Results
Everbright To Launch $2.9 Billion IPO
U.S. Supports New IMF Loan Programs
Bernanke Faces Lawmakers for Second Day
Earnings Watch
SolarWinds, Mellanox Technologies: Biggest Price Decliners (SWI, MLNX)
Snack-Food Makers Lance, Snyder's to Merge
BlueLinx Holdings, Lance: Biggest Price Gainers (BXC, LNCE)
Goldman Sachs Group, JPMorgan Chase: Money Flow Leaders (GS, JPM)
AutoNation's Profit Rises 29%
Revenue Rises at the Times
UPS Profit Surges
Bernanke's Balancing Act
ABB Profit Drops 8%
Crude Rises on Storm Worries
House Passes Jobless Extension
Union Pacific's Profit Rises
Hynix Swings to Profit
Capital Fund Takes AgBank Stake
Safeway Lowers Outlook
Conoco to Book Charge for  German Refinery
St. Jude Earnings Climb On Heart-Rhythm Devices
Zimmer Profit Hit by Charges
Baxter's Profit Drops 8.9%
Smartphone Shift Lifts Qualcomm's Net
Royal Caribbean Posts Profit
Swedbank Returns to a Profit
Janus Profit Soars 91% on Management-Fee Jump
Five of Six Greek Banks Seen Passing Test
SolarWinds, Mellanox Technologies: Biggest Price Decliners (SWI, MLNX)
Stocks in Europe Climb
BlueLinx Holdings, Lance: Biggest Price Gainers (BXC, LNCE)
Morgan Stanley, SPDR Trust: Money Flow Leaders (MS, SPY)
BofA to Sell Warburg Fund Stakes
Medco Profit Up 14%
Xerox Profit Jumps 62%
Eli Lilly Profit Rises 16%; Bristol Posts 5.7% Drop
Daiwa Expects Bigger Asia Revenue
Cigarette Makers Raise Outlook
Couche-Tard Raises Casey's Bid
Hershey Profit Drops 34%
Japan Bond Yields Fall After Auction
Asia Ends Mixed on Bernanke, Yen
Gold Climbs Near $1,200
Ocado Faces Retail Race to Withdraw Offers
Elan's Net Loss Widens
3M Profit Jumps as Sales Rebound
Dubai World Presents Debt Plan to Creditors
U.K. Posts Strong Retail Sales
Storm Claims Hit Travelers Profit
Netflix's Net Jumps, Shares Fall
Air Products Net Doubles
Starwood's Profit Falls 15%
Altria Profit Rises Slightly
Danaher Profit Rises 26%
SABMiller Sells Less Beer
Volvo Profits From More Orders
Banks Deposit Fewer Funds at ECB
Investors in Gulf Oil Well Distance Themselves From Spill
Probe Extends to BP Managers
Windows 7 Boosts Microsoft
Gunmen Attack Russia Power Station
Merkel Defends Cuts as Ratings Fall
Deutsche Bank Is Fined $7.5 Million
German Bond Sale Fails to Impress
Europe, Asia Mostly Higher
IMF Sees Euro-Zone Debt Slowing Growth
Euro Rally Is Prelude to a Fall
Copper Comes Cheaper in London
Commodities Fall as China Cools Growth
Pay Czar to Bash Bank Payments
Reckitt to Buy Durex Maker SSL
Julius Baer Eyes New Markets
Strong Swiss Franc Hits SNB
AIG Picks Arrangers for AIA Listing
Data Underline Banks' Dependency on ECB
Gold Prices Tread Water
Profits Rise, Lending Static at Regional Banks
EMC Will Seek Acquisitions
Coca-Cola Profit Rises 16%
Crude Drops on Surprise Inventory Gains
Morgan Stanley's Earnings Take Off
Piper Jaffray Profit Tumbles
Turkey Shuts Bombed Pipeline
Bernanke Prepared to Take New Steps
Oil Firms to Create Spill-Response System
EBay's Turnaround Slow
Starbucks Net Climbs
Consumer Agency Battle Looms
Metadatos:
  - id: nifty_108
  - date: 2010-07-22 00:00:00
  - context: date,open,high,low,close,adj_close,volume,pct_change,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma
  - label: Rise
  - pct_change: 0.0087



---
**Búsqueda filtrada 5**

In [29]:
query = "economic crisis"

metadata_filter = {
    "label": "Fall"
}

print(f"{R}Consulta:{E}", query)

print(f"{A}Filtro:{E}", metadata_filter)

results = filtered_vector_store.search(
    query=query,
    metadata_filter=metadata_filter
)

mostrar_resultados(results)

Consulta: economic crisis
Filtro: {'label': 'Fall'}
==============================
Resultado #1
Score: 0.4059
Texto:
Mylan Set to Lose in $26 Billion Hostile Takeover Battle for Perrigo
India Shares Fall Along With Rest of the Region
Deutsche Bank Names New Head of Corporate, Investment Bank in Asia Pacific
Ethan Allen’s Chief in Fight of His Life
Copper Swoon Presses Glencore, Other Miners
Stock Decline Picks Up Steam
Nordstrom Earnings Fall Sharply
Fed Weighs Tightening Revolving-Door Curbs
LoanDepot Postpones IPO
Fischer: Strong Dollar Delayed Rate Rise, but Fed Could Move in December
Hottest Energy Trade: A Ride Aboard the Colonial Pipeline
China’s Stock Crackdown: ‘Kill the Chicken to Scare the Monkey’
Activist Investors Seek Changes to ITG Board
Warren Buffett Has an Image Problem
Petrobras Reports Third-Quarter Loss
Peru’s Central Bank Holds Interest Rate Steady
Calpers Sells $3 Billion of Real-Estate Holdings to Blackstone Unit
Brazil’s Inflation Struggles Spark Concerns About ‘Fiscal Dominance’
Yum Brands Reports Growth in China Sales
Asian Morning Briefing: Stocks Fall as Investors Study Central Bank Clues
El Pollo Loco Lowers Guidance As Sales Growth Slows
Farmland Prices Decline Across Parts of Midwest
Planet Fitness Raises Outlook
If Spain’s Economy Is Doing Well, Why Aren’t Its Banks?
Party City Logs Weak Retail Sales
Fossil Cuts Outlook, Profit Falls 45%
Chile’s Central Bank Leaves Monetary-Policy Rate Unchanged
Dollar Slips Against Euro and Yen
Energy Future Leaps Ahead with Fidelity Pact
Rolls-Royce Shares Dive After Earnings Outlook Warning
WSJ Survey: Economists See Downside Risks Receding
Economists Overwhelmingly Expect Fed to Raise Interest Rates in December
Grainger Shares Decline as Outlook Disappoints
Why Are Real Interest Rates So Low?
Why US Unemployment is Not Done Falling
Oil Prices Slide as Crude Inventory Rises More Than Expected
BAE Systems Cuts Earnings Outlook
OPEC Oil Output Falls on Iraqi Export Woes
Gold Prices Fall to Lowest Levels in Over Five Years
Canada’s Biggest Pension Fund Generates 1.6% Quarterly Return
EPA Clears GE Plan to End Dredging of PCBs From Hudson
Natural Gas Inches Lower
Fantasy-Sports Site FanDuel Fights Order to Shut Down
ECB’s Mersch: Regulators Should Be Mindful of Burden Placed on Banks
Dudley: Can’t Say When Fed Will Raise Rates
Copper Prices Hit Six-Year Low
Mexican Retailers On a Roll as Shopping Weekend Nears
Fed Shouldn’t Be Locked Into Gradual Rate-Hike Path: Bullard and Lacker
Fed’s Evans Stays Cautious on Rate Increases
U.S. Budget Deficit Edges Higher in October
Roche Plans to Exit Four Plants as Focus Shifts to Specialty Drugs
ECB’s Weidmann: Reserve Quantitative Easing for Exceptional Circumstances
Deutsche Bank Reshuffles Top Ranks of Investment Bank
Bank of America Says Leitch Will Be New Counsel
U.S. Natural-Gas Inventories Seen Up in Week
Merck Loses Appeal in Cubicin Patent Case
Viacom Revenue Falls on Weak Film Segment, Cable Costs
Canada’s Oil Producers Brace for Latest Test: Higher Carbon Taxes
Case for U.K. Rate Rise Some Way From Being Made, Says BOE’s Haldane
Low Inflation Keeps Bank of Mexico on Hold
U.S. Jobless Claims Unchanged Last Week
NYSE Challenges Fairness of ‘Flash Boys’ Exchange
U.S. Crude-Oil Supplies Rise; Gasoline Inventories Fall
KanAm Grund Inks $15 Million Athens Property Deal With OPAP SA
Heavy-Equipment Dealer Finning Slashes 1,100 Jobs
Manulife Profit Falls 43% on Charges
Hip Tastemakers Choose a Traditional  House
Hertz Adds New Executives
WSJ Survey: Fed Likely on Hold at Least Three Months After Liftoff
Globalization and Central Banking
Diageo Seeks Consumer Research to Help Reverse Sales Slump
U.S. Crude-Oil Inventories Seen Up in Week
Anglo American Shakes Up Management Team
Lacker: Central Bank Can Influence Inflation Through Interest Rates
Manchester United Revenue Soars With Return to Champions League
Eurozone Industrial Output Falls
Yellen Says It Is Critical to Assess How Monetary Policy Works in Post-Crisis World
Banco do Brasil Results Miss Expectations
Molson Expects More Leverage From MillerCoors Deal
Bullard: Fed’s Goals Have Been Met, Yet Policy Remains Accommodative
Noble Group’s Profit Plunges, Finance Chief Resigns
Barrick Gold to Sell Noncore Assets for $720 Million
Encana Posts Another Steep Quarterly Loss
Advance Auto Says CEO to Retire, Adds Starboard CEO to Board
Kohl’s Stock Rises on Earnings Beat, Sales Increase
Liberty Media to Reclassify Shares Into Three Tracking-Stock Groups
Germany’s Merck Lifts Outlook as Profit Jumps
United Technologies Sets Accelerated Buyback
Hannon’s Take: On the Fed, ECB Borders
Energizer Profit, Sales Fall
ECB’s Mario Draghi Reasserts Readiness to Expand Stimulus
Reforming the ECB
Hermès Sales Lifted by Japan, Western Europe
Hong Kong Outshines Other Asian Markets
Dollar Flat Against Yen, Australian Dollar Jumps
Philippine Central Bank Leaves Rates Unchanged
The ECB Should Exit the Troika
SABMiller Hammered by Currencies, Weak Volume
Private Economists Think BOJ Is Too Optimistic on Inflation
Even Janet Yellen Gets No Respect
Burberry Reports Rise in Profit
China Changes Its Currency-Market Ways
Australians Wonder if Job Surge Will Last
RWE Profit Hurt by Low Prices, Tax
Paninvest Seeks $500 Million From Sale of Insurance Business
Oil Prices Make Slippery Gains In Asia
Gold Demand Rose 8% in Third Quarter
Wal-Mart’s Black Friday: No Longer a Five-Day Affair
Metadatos:
  - id: nifty_1156
  - date: 2015-11-12 00:00:00
  - context: date,open,high,low,close,adj_close,volume,pct_change,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma
  - label: Fall
  - pct_change: -0.0112

==============================
Resultado #2
Score: 0.4009
Texto:
U.S. architecture index up slightly in December
Research and Markets: 2010 Worldwide Petrochemical Manufacturing Industry Report with 2011 Forecasts
The Top Five Economic Threats to America in 2010
NSBA 2009 Year-End Economic Report: Small Businesses Still Struggling
South Korean markets at 0500 GMT
TREASURIES-Edge up in Asia on bargain hunters
Hong Kong, China stocks down as banks weigh
Mauritius economy may grow 4.3 pct in 2010- finmin
Indian shares up 0.3 pct; Wipro beats street view
Taiwan's China Steel to raise prices for March
Japan govt warns of deflation, sticks to economy view
Global slide in '09 economic freedom holds risks-index
The Recovery of 2010: How a rise in drilling across the U.S. will hamper the Haynesville
Nikkei slips as brokerages drop; China weighs
MONEY MARKETS-S.Korea basis wider, NZ swaps curve steepens
Rich need to show poor CO2 deal won't hit economy
Swiss stocks - Factors to watch on Jan 20
UPDATE 3-Japan PM: Want to avoid sharp bond yield rises
Europe Factors-Stocks set to extend gains; techs eyed
Nidec Extends Sales Reach Into Guangzhou, China
China Evergrande sets dlr bond price guidance -source
Taiwan's Nanya Tech keeps '10 capex unchanged
Indian shares turn negative; had been up 0.6 pct
PREVIEW-State Bank of India, ICICI Q3 net seen hit by bond moves
Builder Sino-Thai sees higher profits this year
Japan Kan: Risk of another recession still exists
JGB futures dip; curve stays steep before 20-yr sale
FOREX-Euro hits 5-mth low vs dlr, China dents risk trades
REG-Bankers Petroleum Limited: Bankers Petroleum Ltd. Director Shareholding
REG-SVM UK Active Fund: Net Asset Value(s)
REG-SVM Global Fund PLC: Net Asset Value(s)
REG-Innovise PLC: Issue of Equity and Holding in Company
UK Stocks -- Factors to watch on Jan 20
China stocks end down 2.9 pct on lending curb fears
GenRe pays to settle on AIG fraud role -report
Nikkei slips 0.3 pct as brokerages drop;China weighs
GenRe pays to settle on AIG fraud role: report
UPDATE 1-China's CIC says hot money pressuring emerging markets
Moody's keeps outlook for J-REIT sector at negative
Japan corp fund demand weak - BOJ's Shirakawa quoted
DENIS THIERY BECOMES CHAIRMAN AND CHIEF EXECUTIVE OFFICER OF NEOPOST
TIMELINE-China pulls in reins on lending as economy booms
China's CIC in talks for deals in Brazil, Mexico
U.S. has met with China on Internet freedom
CIC expects U.S. dollar to fall when U.S. economy recovers
Studios even more afraid of unsolicited scripts
Research and Markets: China Soft Drinks, Mineral Waters Industry Profile Includes a List of Top 100 Enterprises in the Sector
Research and Markets: New Report Gives Professional Advisory on the Development Trends of China's Phosphate Fertilizer Market in 2009-2012
Belgian Taminco's IPO seen at 10-20 eur/shr -paper
HK stocks skid to near 1-mth closing low, led by banks
 Cardiff is UK's Card Fraud Capital
European shares fall; China loan curb worries
AU Optronics Announces Purchase of FED-related Assets and Technology from Field Emission Technologies
DIARY - S&P; 500 Corporate Earnings Month Ahead
Beijing tells ICBC to raise reserve ratio -sources
Germany's Merkel says economic crisis not over yet
DIARY - S&P; 500 Corporate Earnings form Jan 20 - Jan 27
REG-DB X-TRACKERS MSCI WORLD TRN INDEX ETF Net Asset Value(s)
ECB's Stark says economy could ease in H1 from H2 2009
DIARY - S&P; 500 Corporate Earnings for Wednesday Jan 20, 2010
REG-World Trust Fund Net Asset Value(s)
DIARY - Non-S&P; 500 Earnings for Wednesday Jan 20, 2010
DIARY - Non-S&P; 500 Earnings from Jan 20, 2010  - Feb 03, 2010
REG-DB x-trackers MSCI JAPAN TRN INDEX ETF Net Asset Value(s)
REG-db x-trackers DJ EURO STOXX50 ETF Net Asset Value(s)
REG-db x-trackers DJ EURO STOXX 50 INDEX ETF 1C Net Asset Value(s)
HK, China stocks skid to near 1-mth closing lows, banks lead
Research and Markets: China Stone, Sand & Clay Quarrying Industry Profile 2010 Available Now for Analysis
DEALTALK-Temasek, China rebuff debt-heavy RUSAL's IPO pitch
REG-PowerShares RAFI1000: Net Asset Value(s)
REG-PowerShares RAFI Eur: Net Asset Value(s)
REG-PowerShares Cln Engy: Net Asset Value(s)
REG-PowerShares UK 100: Net Asset Value(s)
Moody's:Italian leasing ABS performance continued to deteriorate
REG-PowerShrs RAFI DevEu: Net Asset Value(s)
REG-PowerShares Dyn UK: Net Asset Value(s)
Merkel says G20 needs to act on big banks' influence
FTSE slips as China action on lending hurts miners
The Conference Board(R) France Business Cycle Indicators(SM)
Research and Markets: China Dairy Industry Profile 2010 Will Enable Readers to Make a Comparison on the Development Condition and Investment Potential of Dairy Industry in China
FOREX-Euro hits 5-month lows vs dollar, sterling
S.Korea KOGAS to invest $6.5 bln in Iraq oil project
China's Sinofert warns of net loss for 2009
Temasek, China rebuff debt-heavy RUSAL's IPO pitch
Samsung Life's record IPO in May or June: source
China banks lend 1.1 trln yuan in first 2 weeks on 2010-sources
Soco says in talks on sale of stake in DRC block
GLOBAL MARKETS-China lending worry hits stocks; euro tumbles
Dr. Reddy`s Q3 FY10 Financial Results
China's Baidu sues US domain registrar after hack
UPDATE 3-Wipro Q3 beats street, confirms outsourcing revival
Taiwan's Powerchip returns to profit in Q4
Russia car market to recover from slump by 2016-PWC
 Munters AB: Presentation for investors, analysts and media
European shares slip on China lending concerns
 Sugar Industry Will Play Major Role in Global Energy Market; a "Navigating the Currents of Change" Webcast on
Portable Fuel Cell Market to Reach $2.3 Billion by 2016, According to Pike Research
Research and Markets: China Fruit & Vegetables Industry Profile 2010 is the First Report to Adopt ISIC (International Standard Industrial Classification of All Economic Activities)
REG-BlackRock New Engy: Portfolio Update
China Inc's global growing pains
India's Exim Bank hires banks for dlr bond -source
Acetic Acid: 2010 World Market Outlook And Forecast Been Recently Released by MarketPublishers.com
UPDATE 3-China's CIC says hot money pressuring emerging markets
German 2-yr debt sale attracts demand from banks
China's XD Electric prices IPO at top of range
REG-db x-trackers DB HEDGE FUND INDEX ETF SHARECLASS 3C Net Asset Value(s)
ANALYSIS-Unrest risk clouds Cameroon's "bright future"
ANALYSIS-Unrest risk clouds Cameroon's "bright future"
REG-DB X-TRACKERS MSCI WORLD TRN INDEX ETF Net Asset Value(s)
FACTBOX-How UK retailers fared over Christmas
China's support for more Iran sanctions in doubt
UPDATE 1-Dubai World Istithmar unit CEO resigns, CIO steps in
REG-DB x-trackers MSCI JAPAN TRN INDEX ETF Net Asset Value(s)
WRAPUP 2-China tries to curb lending and avoid overheating
Snap analysis: Financial reform push shaken as Obama confers
Google attack puts spotlight on China's "red" hackers
REG-Finsbury Worldwide: Net Asset Value(s)
REG-db x-trackers DJ EURO STOXX50 ETF Net Asset Value(s)
U.S. stock futures signal dip; banks earnings eyed
REG-db x-trackers DJ EURO STOXX 50 INDEX ETF 1C Net Asset Value(s)
REG-ABN AMRO BANK N.V. EPT Disclosure
Brent crude futures down $1 on tight China credit
REG-ABN AMRO BANK N.V. EPT Disclosure
REG-ABN AMRO BANK N.V. EPT Disclosure
Research and Markets: The Indian Geospatial Industry Report 2009
REG-ABN AMRO BANK N.V. EPT Disclosure
Acrylic Acid: 2010 World Market Outlook And Forecast Been Recently Released by MarketPublishers.com
Deutsche Bank to unveil German equity fund details
Timeline: China pulls in reins on lending as economy booms
REG-ABN AMRO BANK N.V. EPT Disclosure
REG-ABN AMRO BANK N.V. EPT Disclosure
RPT-Deutsche Bank to unveil German equity fund details
Research and Markets: 2010 Worldwide Cookie, Cracker & Pasta Mfg Industry Report Now Available
Galaxy Announces Management Update & Selected Unaudited 2009 Fourth Quarter Financial Data
REG-Fidelity European: Net Asset Value(s)
REG-Fidelity AsianValues: Net Asset Value(s)
REG-Gartmore Managed & Administered Investment Trusts: Net Asset Value(s)
Research and Markets: Survival Strategies for Teaching Large Classes
 Regulatory Changes for Options Traders Expected to Be Costly
The Coca-Cola Company, TechnoServe and the Gates Foundation Partner to Boost Incomes of 50,000 Small-Scale Fruit Farmers in East Africa
Xerox Acquires Irish Business Systems: Expands SMB Channel in the Republic of Ireland and Northern Ireland
REG-BlackRock Investment Trusts: Net Asset Value(s)
BHP gives bullish demand outlook
Scenarios: What comes next for the U.S. and Haiti?
Donors must stick with Haiti: World Bank chief
Haiti information service launched by Thomson Reuters Foundation
REG-BlackRock World Mng: Net Asset Value(s)
REG-BlackRock New Engy: Net Asset Value(s)
REG-BlackRock Smll Cos: Net Asset Value(s)
REG-BlackRock Latin Am: Net Asset Value(s)
REG-BlackRock Com: Net Asset Value(s)
Greece looking into popular bond - finmin
SE Asia Stocks-Indonesia, Malaysia hit 22-month highs
RPT-PREVIEW-Canada's December CPI seen at +1.6 pct y/y
Business Update: China bank fears
REG-Alliance Trust PLC: Net Asset Value(s)
Indian shares drop 2nd day; ONGC, Reliance fall
Research and Markets: The Coagulation Testing Market: US, Europe, Japan - Emerging Business Opportunities and Market Expansion Strategies for Suppliers
REG-Gartmore Irish: Net Asset Value(s)
Brazil's BNDES may buy Hypermarcas stake-report
 Santander Announces Results of Cash Tender Offer for Abbey National plc 7.95% Term Subordinated Securities Due 2029
FOREX-Euro/dollar hits 5-mth low, breaks tech support
BNY Mellon Reports Fourth Quarter Continuing EPS of $0.59 or $712 Million; Net Benefit of $0.04 Due To:
Surging Popularity of ReTrakÂ® Products Drives Expansion of Emerge Technologies
Women in Technology Hosts Areas Leading CIOs
 MetaPower Announces Changes to Capital Structure
Huawei shows China's scope for organic growth
Krung Thai Bank Q4 profit up, higher than forecast
Research and Markets: 2010 Worldwide Book Publishing Industry Report
Crosstex Energy Completes Blackstone/GSO Transaction; Appoints Dwight Scott to Board of Directors
China tries to curb lending and avoid overheating
Research and Markets: 2010 Worldwide Cable Television Networks Industry Report
REG-db x-trackers S&P; EUROPE 350 SHARIAH ETF Net Asset Value(s)
REG-DB X-Trackers - DJ STOXX 600 FOOD & BEVERAGE ETF Net Asset Value(s)
China punishes some banks lending too much: sources
REG-db x-trackers S&P; JAPAN 500 SHARIAH ETF Net Asset Value(s)
Research and Markets: This Essential Worldwide Banknote Industry Research Report Provides a Better Understanding of Banknote Demand, Issuance and Factors Affecting the Production Process
S.Africa's rand extends losses vs dollar
REG-db x-trackers MSCI PACIFIC EX JAPAN TRN INDEX ETF Net Asset Value(s)
EcoBlu Products to Exhibit at the International Builder's Show
REG-db x-trackers S&P; 500 SHARIAH ETF Net Asset Value(s)
REG-db x-trackers DOW JONES ISLAMIC MARKET TITANS 100 ETF Net Asset Value(s)
REG-db x-trackers S&P; Global Infrastructure ETF Net Asset Value(s)
REG-db x-trackers MSCI Russia 25% capped Index ETF Net Asset Value(s)
Huawei shows China's scope for organic growth
REG-db x-trackers FTSE All-World ex UK ETF Net Asset Value(s)
REG-db x-trackers FTSE Vietnam ETF Net Asset Value(s)
Research and Markets: Electric Power Transmission and Distribution Equipment - a Worldwide Market Review
RPT-US Treasury delays first step in new capital rules
 Hoggan & Associates Inc.: 'Clean' Companies Beat Overall Canadian and U.S. Stock Markets in 2009
 TTEngines' Top Exec Returns to China
Securities America Ends 25th Year With a Bang
China Information Security Technology Wins Software Award
REG-DB X-Trackers - DJ STOXX 600 INDUSTRIAL GOODS ETF Net Asset Value(s)
National Capital Bank of Washington Announces Strong Year-End Earnings
Click Commerce to Automate Financial Interest Disclosures for Researchers at The Pennsylvania State University
U.S. Bancorp Reports Net Income for the Fourth Quarter of 2009
Unidym Completes Licensing Agreements to Expand Use of its Carbon Nanotube IP in Diverse Array of Applications
Made-in-China.com, a Global B2B E-Commerce Platform Providing International Trading Services to Suppliers and Buyers of Chinese Products, Announces 360jmg, LLC as Public Relations and Advertising Agency of Record
REG-db x-trackers DJ STOXX 600@ Banks Short Daily ETF Net Asset Value(s)
NCR Sells 50,000th NCR SelfServ ATM, Helps Banks around the World Deliver Improved Customer Service
UPDATE 1-Greece looking into all borrowing options - finmin
RPT-DAVOS-SPECIAL REPORT-China Inc's global growing pains
BNY Mellon earnings rise on higher assets
Research and Markets: An Essential Report on Global Dialysis Market Trends and Opportunities
REG-DB X-Trackers - DJ EURO STOXX 50 SHORT DAILY ETF Net Asset Value(s)
 Netuitive Reports Record Results for 2009
REG-db x-trackers FTSE 100 Short Daily ETF Net Asset Value(s)
 Netuitive Reports Record Results for 2009
Research and Markets: Brain Tumor - Drug Pipeline Analysis and Market Forecasts to 2016
Canada dollar falls vs U.S. dollar after Canada CPI
Avanza Bank Preliminary Finacial Statement 2009
REG-db x-trackers S&P; 500 Inverse Daily ETF Net Asset Value(s)
India's Dec oil product sales up 2.7 pct y/y - govt
REG-db x-trackers MSCI ASIA EX JAPAN TRN INDEX ETF Net Asset Value(s)
REG-DB X-Trackers - DJ STOXX GLOBAL SELECT DIVIDEND 100 ETF Net Asset Value(s)
UPDATE 1-Market Chatter -- Corporate finance press digest
Research and Markets: Rheumatoid Arthritis - Drug Pipeline Analysis & Forecasts Show a Significant Growth Till 2015
Dollar extends gains, dlr index hits 1-month high
Immofinanz hopes for dividend payout in 2011-12
Chi-X, BATS winning in Europe stock market rivalry
Sify Technologies to Report Third Quarter Financial Results for Fiscal Year 2009-10 on Wednesday, January 27, 2010
REG-Baring Emerging Eur: Net Asset Value(s)
 Cineplex Galaxy Income Fund Announces Timing of Fourth Quarter and Year End Earnings Release and Conference Call
MortgageBrokers.com announces stock repurchase program
ecobee Raises $6.73 Million in Funding from The Ontario Emerging Technologies Fund, JLA Ventures and Tech Capital
West to Present at Jefferies Investor Conference
Retirees Polled On 2010 U.S. Economic Outlook:

# Conclusión parcial

En esta segunda parte se logró implementar correctamente un FilteredVectorStore, permitiendo realizar búsquedas semánticas utilizando filtros de metadatos.

A diferencia del VectorStore básico, esta versión permite recuperar información más específica dependiendo de atributos como fecha, contexto, etiqueta o cambios porcentuales, lo que ayuda a organizar mejor los resultados obtenidos.

Aunque apenas estamos comenzando a trabajar con este tipo de herramientas, la actividad permitió entender de forma más clara cómo funcionan los sistemas modernos de recuperación de información basados en embeddings y filtros estructurados.

Además, se pudo observar cómo la combinación entre búsqueda semántica y metadatos mejora la precisión de las consultas, acercándonos al funcionamiento real de muchas aplicaciones actuales de inteligencia artificial y procesamiento de lenguaje natural.



---



---



---

⚠️ Disclaimer Algunas partes de este notebook fueron asistidas mediante herramientas de inteligencia artificial.

Estas secciones han sido revisadas, comprendidas y adaptadas para cumplir con los objetivos de la actividad.

Las partes asistidas están claramente identificadas con el siguiente icono: #⚠️